#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AirWall_Spline_new

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_AirWall_Spline_new.BP_AirWall_Spline_new_C.ExecuteUbergraph_BP_AirWall_Spline_new
// 0x00B8 (0x00B8 - 0x0000)
struct BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12[0x2];                                       // 0x0012(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USplineComponent*                       CallFunc_GetComponentByClass_ReturnValue;          // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetLocationAtSplinePoint_ReturnValue;     // 0x0030(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetNumberOfSplinePoints_ReturnValue;      // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UMergedSplineMeshComponent* MergedMeshComp)> K2Node_CreateDelegate_OutputDelegate; // 0x0044(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetLocationAtSplinePoint_ReturnValue_1;   // 0x0058(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetNumberOfSplinePoints_ReturnValue_1;    // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_Conv_VectorToVector2D_ReturnValue;        // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_1;           // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x3];                                       // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASolarGameMode*                         CallFunc_GetSolarGameMode_ReturnValue;             // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x3];                                       // 0x0081(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                K2Node_Event_Location;                             // 0x0084(0x000C)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMergedSplineMeshComponent*             K2Node_CustomEvent_MergedMeshComp;                 // 0x0090(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetSplineLength_ReturnValue;              // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x00A5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A6[0x2];                                       // 0x00A6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select_Default;                             // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Round_ReturnValue;                        // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new) == 0x000008, "Wrong alignment on BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new");
static_assert(sizeof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new) == 0x0000B8, "Wrong size on BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, EntryPoint) == 0x000000, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, Temp_int_Variable) == 0x000004, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x000008, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, Temp_bool_Variable) == 0x000010, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_IsServer_ReturnValue) == 0x000011, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_IsServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, K2Node_Event_DeltaSeconds) == 0x000014, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, Temp_int_Variable_1) == 0x000018, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_IsValid_ReturnValue) == 0x00001C, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_Add_IntInt_ReturnValue_1) == 0x000020, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_GetComponentByClass_ReturnValue) == 0x000028, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_GetLocationAtSplinePoint_ReturnValue) == 0x000030, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_GetLocationAtSplinePoint_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_GetNumberOfSplinePoints_ReturnValue) == 0x00003C, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_GetNumberOfSplinePoints_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_Subtract_IntInt_ReturnValue) == 0x000040, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, K2Node_CreateDelegate_OutputDelegate) == 0x000044, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000054, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_GetLocationAtSplinePoint_ReturnValue_1) == 0x000058, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_GetLocationAtSplinePoint_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_GetNumberOfSplinePoints_ReturnValue_1) == 0x000064, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_GetNumberOfSplinePoints_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_Conv_VectorToVector2D_ReturnValue) == 0x000068, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_Conv_VectorToVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_LessEqual_IntInt_ReturnValue_1) == 0x000070, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_LessEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_Array_Add_ReturnValue) == 0x000074, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_GetSolarGameMode_ReturnValue) == 0x000078, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_GetSolarGameMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_IsValid_ReturnValue_1) == 0x000080, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, K2Node_Event_Location) == 0x000084, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::K2Node_Event_Location' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, K2Node_CustomEvent_MergedMeshComp) == 0x000090, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::K2Node_CustomEvent_MergedMeshComp' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x000098, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_GetSplineLength_ReturnValue) == 0x0000A0, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_GetSplineLength_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x0000A4, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_BooleanOR_ReturnValue) == 0x0000A5, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, K2Node_Select_Default) == 0x0000A8, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_Divide_FloatFloat_ReturnValue) == 0x0000AC, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_Round_ReturnValue) == 0x0000B0, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_Round_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new, CallFunc_Conv_IntToFloat_ReturnValue) == 0x0000B4, "Member 'BP_AirWall_Spline_new_C_ExecuteUbergraph_BP_AirWall_Spline_new::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");

// Function BP_AirWall_Spline_new.BP_AirWall_Spline_new_C.SetTilingNum
// 0x0008 (0x0008 - 0x0000)
struct BP_AirWall_Spline_new_C_SetTilingNum final
{
public:
	class UMergedSplineMeshComponent*             MergedMeshComp;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AirWall_Spline_new_C_SetTilingNum) == 0x000008, "Wrong alignment on BP_AirWall_Spline_new_C_SetTilingNum");
static_assert(sizeof(BP_AirWall_Spline_new_C_SetTilingNum) == 0x000008, "Wrong size on BP_AirWall_Spline_new_C_SetTilingNum");
static_assert(offsetof(BP_AirWall_Spline_new_C_SetTilingNum, MergedMeshComp) == 0x000000, "Member 'BP_AirWall_Spline_new_C_SetTilingNum::MergedMeshComp' has a wrong offset!");

// Function BP_AirWall_Spline_new.BP_AirWall_Spline_new_C.SetActorPositionParameter
// 0x000C (0x000C - 0x0000)
struct BP_AirWall_Spline_new_C_SetActorPositionParameter final
{
public:
	struct FVector                                Location;                                          // 0x0000(0x000C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AirWall_Spline_new_C_SetActorPositionParameter) == 0x000004, "Wrong alignment on BP_AirWall_Spline_new_C_SetActorPositionParameter");
static_assert(sizeof(BP_AirWall_Spline_new_C_SetActorPositionParameter) == 0x00000C, "Wrong size on BP_AirWall_Spline_new_C_SetActorPositionParameter");
static_assert(offsetof(BP_AirWall_Spline_new_C_SetActorPositionParameter, Location) == 0x000000, "Member 'BP_AirWall_Spline_new_C_SetActorPositionParameter::Location' has a wrong offset!");

// Function BP_AirWall_Spline_new.BP_AirWall_Spline_new_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_AirWall_Spline_new_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AirWall_Spline_new_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_AirWall_Spline_new_C_ReceiveTick");
static_assert(sizeof(BP_AirWall_Spline_new_C_ReceiveTick) == 0x000004, "Wrong size on BP_AirWall_Spline_new_C_ReceiveTick");
static_assert(offsetof(BP_AirWall_Spline_new_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_AirWall_Spline_new_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

}

