#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BTT_SetBlackBoardKey_Object

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BTT_SetBlackBoardKey_Object.BP_BTT_SetBlackBoardKey_Object_C
// 0x0030 (0x00D8 - 0x00A8)
class UBP_BTT_SetBlackBoardKey_Object_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FBlackboardKeySelector                 BlackboardKey;                                     // 0x00B0(0x0028)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_BP_BTT_SetBlackBoardKey_Object(int32 EntryPoint);
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BTT_SetBlackBoardKey_Object_C">();
	}
	static class UBP_BTT_SetBlackBoardKey_Object_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BTT_SetBlackBoardKey_Object_C>();
	}
};
static_assert(alignof(UBP_BTT_SetBlackBoardKey_Object_C) == 0x000008, "Wrong alignment on UBP_BTT_SetBlackBoardKey_Object_C");
static_assert(sizeof(UBP_BTT_SetBlackBoardKey_Object_C) == 0x0000D8, "Wrong size on UBP_BTT_SetBlackBoardKey_Object_C");
static_assert(offsetof(UBP_BTT_SetBlackBoardKey_Object_C, UberGraphFrame) == 0x0000A8, "Member 'UBP_BTT_SetBlackBoardKey_Object_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_BTT_SetBlackBoardKey_Object_C, BlackboardKey) == 0x0000B0, "Member 'UBP_BTT_SetBlackBoardKey_Object_C::BlackboardKey' has a wrong offset!");

}

