#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BTS_CheckCanSeePlayer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BTS_CheckCanSeePlayer.BP_BTS_CheckCanSeePlayer_C
// 0x0058 (0x00F0 - 0x0098)
class UBP_BTS_CheckCanSeePlayer_C final : public UBTService_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0098(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ASolarBotAIController*                  SelfController;                                    // 0x00A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  ControlledPawn;                                    // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class ABP_SolarCharacterPlayer_C*>     Players;                                           // 0x00B0(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance, HasGetValueTypeHash)
	struct FBlackboardKeySelector                 SeenByPlayer;                                      // 0x00C0(0x0028)(Edit, BlueprintVisible)
	float                                         DistanceCheck;                                     // 0x00E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveTickAI(class AAIController* OwnerController, class APawn* ControlledPawn_0, float DeltaSeconds);
	void ReceiveSearchStartAI(class AAIController* OwnerController, class APawn* ControlledPawn_0);
	void ReceiveActivationAI(class AAIController* OwnerController, class APawn* ControlledPawn_0);
	void ExecuteUbergraph_BP_BTS_CheckCanSeePlayer(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BTS_CheckCanSeePlayer_C">();
	}
	static class UBP_BTS_CheckCanSeePlayer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BTS_CheckCanSeePlayer_C>();
	}
};
static_assert(alignof(UBP_BTS_CheckCanSeePlayer_C) == 0x000008, "Wrong alignment on UBP_BTS_CheckCanSeePlayer_C");
static_assert(sizeof(UBP_BTS_CheckCanSeePlayer_C) == 0x0000F0, "Wrong size on UBP_BTS_CheckCanSeePlayer_C");
static_assert(offsetof(UBP_BTS_CheckCanSeePlayer_C, UberGraphFrame) == 0x000098, "Member 'UBP_BTS_CheckCanSeePlayer_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_BTS_CheckCanSeePlayer_C, SelfController) == 0x0000A0, "Member 'UBP_BTS_CheckCanSeePlayer_C::SelfController' has a wrong offset!");
static_assert(offsetof(UBP_BTS_CheckCanSeePlayer_C, ControlledPawn) == 0x0000A8, "Member 'UBP_BTS_CheckCanSeePlayer_C::ControlledPawn' has a wrong offset!");
static_assert(offsetof(UBP_BTS_CheckCanSeePlayer_C, Players) == 0x0000B0, "Member 'UBP_BTS_CheckCanSeePlayer_C::Players' has a wrong offset!");
static_assert(offsetof(UBP_BTS_CheckCanSeePlayer_C, SeenByPlayer) == 0x0000C0, "Member 'UBP_BTS_CheckCanSeePlayer_C::SeenByPlayer' has a wrong offset!");
static_assert(offsetof(UBP_BTS_CheckCanSeePlayer_C, DistanceCheck) == 0x0000E8, "Member 'UBP_BTS_CheckCanSeePlayer_C::DistanceCheck' has a wrong offset!");

}

