#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GeneralInteractionListConfig

#include "Basic.hpp"

#include "E_Interact_Type_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "BPS_InteractionButtonViewConfig_structs.hpp"
#include "Solarland_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GeneralInteractionListConfig.BP_GeneralInteractionListConfig_C
// 0x01E0 (0x0260 - 0x0080)
class UBP_GeneralInteractionListConfig_C final : public UGeneralInteractionButtonConfigDataAsset
{
public:
	TMap<E_Interact_Type, E_Interact_Type>        NormalToBuff;                                      // 0x0080(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<E_Interact_Type, E_Interact_Type>        BuffToNormal;                                      // 0x00D0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<struct FGameplayTag, struct FBPS_InteractionButtonViewConfig> InteractionConfig;            // 0x0120(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<struct FGameplayTag, struct FGameplayTag> NormalToBuffNew;                                  // 0x0170(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<struct FGameplayTag, struct FGameplayTag> BuffToNormalNew;                                  // 0x01C0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<E_Interact_Type, struct FGameplayTag>    InteractTypeMapTag;                                // 0x0210(0x0050)(Edit, BlueprintVisible)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GeneralInteractionListConfig_C">();
	}
	static class UBP_GeneralInteractionListConfig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GeneralInteractionListConfig_C>();
	}
};
static_assert(alignof(UBP_GeneralInteractionListConfig_C) == 0x000008, "Wrong alignment on UBP_GeneralInteractionListConfig_C");
static_assert(sizeof(UBP_GeneralInteractionListConfig_C) == 0x000260, "Wrong size on UBP_GeneralInteractionListConfig_C");
static_assert(offsetof(UBP_GeneralInteractionListConfig_C, NormalToBuff) == 0x000080, "Member 'UBP_GeneralInteractionListConfig_C::NormalToBuff' has a wrong offset!");
static_assert(offsetof(UBP_GeneralInteractionListConfig_C, BuffToNormal) == 0x0000D0, "Member 'UBP_GeneralInteractionListConfig_C::BuffToNormal' has a wrong offset!");
static_assert(offsetof(UBP_GeneralInteractionListConfig_C, InteractionConfig) == 0x000120, "Member 'UBP_GeneralInteractionListConfig_C::InteractionConfig' has a wrong offset!");
static_assert(offsetof(UBP_GeneralInteractionListConfig_C, NormalToBuffNew) == 0x000170, "Member 'UBP_GeneralInteractionListConfig_C::NormalToBuffNew' has a wrong offset!");
static_assert(offsetof(UBP_GeneralInteractionListConfig_C, BuffToNormalNew) == 0x0001C0, "Member 'UBP_GeneralInteractionListConfig_C::BuffToNormalNew' has a wrong offset!");
static_assert(offsetof(UBP_GeneralInteractionListConfig_C, InteractTypeMapTag) == 0x000210, "Member 'UBP_GeneralInteractionListConfig_C::InteractTypeMapTag' has a wrong offset!");

}

