#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SolarCheatManager

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_SolarCheatManager.BP_SolarCheatManager_C.SolarGM_TestResurrectCapsule
// 0x0028 (0x0028 - 0x0000)
struct BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule final
{
public:
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASCMPlayerState*                        K2Node_DynamicCast_AsSCMPlayer_State;              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x001C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule) == 0x000008, "Wrong alignment on BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule");
static_assert(sizeof(BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule) == 0x000028, "Wrong size on BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule");
static_assert(offsetof(BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule, CallFunc_GetPlayerController_ReturnValue) == 0x000000, "Member 'BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule, CallFunc_K2_GetPawn_ReturnValue) == 0x000008, "Member 'BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule::CallFunc_K2_GetPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule, K2Node_DynamicCast_AsSCMPlayer_State) == 0x000010, "Member 'BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule::K2Node_DynamicCast_AsSCMPlayer_State' has a wrong offset!");
static_assert(offsetof(BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule, CallFunc_K2_GetActorLocation_ReturnValue) == 0x00001C, "Member 'BP_SolarCheatManager_C_SolarGM_TestResurrectCapsule::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");

}

