#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ShieldHitEffectController

#include "Basic.hpp"

#include "Solarland_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ShieldHitEffectController.BP_ShieldHitEffectController_C
// 0x0000 (0x0040 - 0x0040)
class UBP_ShieldHitEffectController_C final : public UShieldHitEffectController
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ShieldHitEffectController_C">();
	}
	static class UBP_ShieldHitEffectController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ShieldHitEffectController_C>();
	}
};
static_assert(alignof(UBP_ShieldHitEffectController_C) == 0x000008, "Wrong alignment on UBP_ShieldHitEffectController_C");
static_assert(sizeof(UBP_ShieldHitEffectController_C) == 0x000040, "Wrong size on UBP_ShieldHitEffectController_C");

}

