#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TL03_BD_FieldHouseC

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TL03_BD_FieldHouseC.BP_TL03_BD_FieldHouseC_C
// 0x0218 (0x04F0 - 0x02D8)
class ABP_TL03_BD_FieldHouseC_C final : public AActor
{
public:
	class UStaticMeshComponent*                   SM_B3_BD_ModuSpacM1;                               // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_B3_BD_ModuSpacM;                                // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight38;                                       // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight37;                                       // 0x02F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight36;                                       // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight35;                                       // 0x0300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight34;                                       // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight33;                                       // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight32;                                       // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight31;                                       // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight21;                                       // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight29;                                       // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight28;                                       // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight27;                                       // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight26;                                       // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight25;                                       // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight24;                                       // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight23;                                       // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight22;                                       // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight30;                                       // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight44;                                       // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight19;                                       // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight48;                                       // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight61;                                       // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight60;                                       // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight59;                                       // 0x03A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight58;                                       // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight49;                                       // 0x03B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight57;                                       // 0x03B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight56;                                       // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight55;                                       // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight54;                                       // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight53;                                       // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight52;                                       // 0x03E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight46;                                       // 0x03E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight45;                                       // 0x03F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight18;                                       // 0x03F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight20;                                       // 0x0400(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight47;                                       // 0x0408(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight16;                                       // 0x0410(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight15;                                       // 0x0418(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight14;                                       // 0x0420(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight13;                                       // 0x0428(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight12;                                       // 0x0430(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight11;                                       // 0x0438(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight51;                                       // 0x0440(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight50;                                       // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight9;                                        // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight17;                                       // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight6;                                        // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight5;                                        // 0x0468(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight10;                                       // 0x0470(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight8;                                        // 0x0478(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight7;                                        // 0x0480(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   FieldHouseC_BPlight;                               // 0x0488(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USolarSpatialAudioRoomStaticMeshComponent* Udini_ChildConponentSM_Audio_Cube_SM_Audio_Cube_1_0; // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Udini_ParentConponentSM_Audio_Cube_SM_Audio_Cube_1_0; // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_B3_PB_MoonCloth05;                              // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_B3_PB_MoonCloth04;                              // 0x04A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_B3_PB_MoonCloth03;                              // 0x04B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_B3_PB_MoonCloth02;                              // 0x04B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_SolarItemSpawner11;                             // 0x04C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_SolarItemSpawner5;                              // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_SolarItemSpawner10;                             // 0x04D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_SolarItemSpawner8;                              // 0x04D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_B3_BD_FieldHouseC_In;                           // 0x04E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_B3_BD_FieldHouseC_Out;                          // 0x04E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TL03_BD_FieldHouseC_C">();
	}
	static class ABP_TL03_BD_FieldHouseC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TL03_BD_FieldHouseC_C>();
	}
};
static_assert(alignof(ABP_TL03_BD_FieldHouseC_C) == 0x000008, "Wrong alignment on ABP_TL03_BD_FieldHouseC_C");
static_assert(sizeof(ABP_TL03_BD_FieldHouseC_C) == 0x0004F0, "Wrong size on ABP_TL03_BD_FieldHouseC_C");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SM_B3_BD_ModuSpacM1) == 0x0002D8, "Member 'ABP_TL03_BD_FieldHouseC_C::SM_B3_BD_ModuSpacM1' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SM_B3_BD_ModuSpacM) == 0x0002E0, "Member 'ABP_TL03_BD_FieldHouseC_C::SM_B3_BD_ModuSpacM' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight38) == 0x0002E8, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight38' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight37) == 0x0002F0, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight37' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight36) == 0x0002F8, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight36' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight35) == 0x000300, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight35' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight34) == 0x000308, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight34' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight33) == 0x000310, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight33' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight32) == 0x000318, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight32' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight31) == 0x000320, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight31' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight21) == 0x000328, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight21' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight29) == 0x000330, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight29' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight28) == 0x000338, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight28' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight27) == 0x000340, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight27' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight26) == 0x000348, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight26' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight25) == 0x000350, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight25' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight24) == 0x000358, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight24' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight23) == 0x000360, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight23' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight22) == 0x000368, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight22' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight30) == 0x000370, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight30' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight44) == 0x000378, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight44' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight19) == 0x000380, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight19' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight48) == 0x000388, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight48' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight61) == 0x000390, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight61' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight60) == 0x000398, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight60' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight59) == 0x0003A0, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight59' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight58) == 0x0003A8, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight58' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight49) == 0x0003B0, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight49' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight57) == 0x0003B8, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight57' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight56) == 0x0003C0, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight56' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight55) == 0x0003C8, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight55' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight54) == 0x0003D0, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight54' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight53) == 0x0003D8, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight53' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight52) == 0x0003E0, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight52' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight46) == 0x0003E8, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight46' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight45) == 0x0003F0, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight45' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight18) == 0x0003F8, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight18' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight20) == 0x000400, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight20' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight47) == 0x000408, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight47' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight16) == 0x000410, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight16' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight15) == 0x000418, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight15' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight14) == 0x000420, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight14' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight13) == 0x000428, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight13' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight12) == 0x000430, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight12' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight11) == 0x000438, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight11' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight51) == 0x000440, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight51' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SpotLight50) == 0x000448, "Member 'ABP_TL03_BD_FieldHouseC_C::SpotLight50' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight9) == 0x000450, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight9' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight17) == 0x000458, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight17' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight6) == 0x000460, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight6' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight5) == 0x000468, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight5' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight10) == 0x000470, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight10' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight8) == 0x000478, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight8' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, RectLight7) == 0x000480, "Member 'ABP_TL03_BD_FieldHouseC_C::RectLight7' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, FieldHouseC_BPlight) == 0x000488, "Member 'ABP_TL03_BD_FieldHouseC_C::FieldHouseC_BPlight' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, Udini_ChildConponentSM_Audio_Cube_SM_Audio_Cube_1_0) == 0x000490, "Member 'ABP_TL03_BD_FieldHouseC_C::Udini_ChildConponentSM_Audio_Cube_SM_Audio_Cube_1_0' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, Udini_ParentConponentSM_Audio_Cube_SM_Audio_Cube_1_0) == 0x000498, "Member 'ABP_TL03_BD_FieldHouseC_C::Udini_ParentConponentSM_Audio_Cube_SM_Audio_Cube_1_0' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, BP_B3_PB_MoonCloth05) == 0x0004A0, "Member 'ABP_TL03_BD_FieldHouseC_C::BP_B3_PB_MoonCloth05' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, BP_B3_PB_MoonCloth04) == 0x0004A8, "Member 'ABP_TL03_BD_FieldHouseC_C::BP_B3_PB_MoonCloth04' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, BP_B3_PB_MoonCloth03) == 0x0004B0, "Member 'ABP_TL03_BD_FieldHouseC_C::BP_B3_PB_MoonCloth03' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, BP_B3_PB_MoonCloth02) == 0x0004B8, "Member 'ABP_TL03_BD_FieldHouseC_C::BP_B3_PB_MoonCloth02' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, BP_SolarItemSpawner11) == 0x0004C0, "Member 'ABP_TL03_BD_FieldHouseC_C::BP_SolarItemSpawner11' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, BP_SolarItemSpawner5) == 0x0004C8, "Member 'ABP_TL03_BD_FieldHouseC_C::BP_SolarItemSpawner5' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, BP_SolarItemSpawner10) == 0x0004D0, "Member 'ABP_TL03_BD_FieldHouseC_C::BP_SolarItemSpawner10' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, BP_SolarItemSpawner8) == 0x0004D8, "Member 'ABP_TL03_BD_FieldHouseC_C::BP_SolarItemSpawner8' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SM_B3_BD_FieldHouseC_In) == 0x0004E0, "Member 'ABP_TL03_BD_FieldHouseC_C::SM_B3_BD_FieldHouseC_In' has a wrong offset!");
static_assert(offsetof(ABP_TL03_BD_FieldHouseC_C, SM_B3_BD_FieldHouseC_Out) == 0x0004E8, "Member 'ABP_TL03_BD_FieldHouseC_C::SM_B3_BD_FieldHouseC_Out' has a wrong offset!");

}

