#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ccsconn

#include "Basic.hpp"


namespace SDK::Params
{

// Function ccsconn.StateProducer.OnConnected
// 0x0004 (0x0004 - 0x0000)
struct StateProducer_OnConnected final
{
public:
	int32                                         ConnectionId;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(StateProducer_OnConnected) == 0x000004, "Wrong alignment on StateProducer_OnConnected");
static_assert(sizeof(StateProducer_OnConnected) == 0x000004, "Wrong size on StateProducer_OnConnected");
static_assert(offsetof(StateProducer_OnConnected, ConnectionId) == 0x000000, "Member 'StateProducer_OnConnected::ConnectionId' has a wrong offset!");

// Function ccsconn.StateProducer.OnDisconnected
// 0x0004 (0x0004 - 0x0000)
struct StateProducer_OnDisconnected final
{
public:
	int32                                         ConnectionId;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(StateProducer_OnDisconnected) == 0x000004, "Wrong alignment on StateProducer_OnDisconnected");
static_assert(sizeof(StateProducer_OnDisconnected) == 0x000004, "Wrong size on StateProducer_OnDisconnected");
static_assert(offsetof(StateProducer_OnDisconnected, ConnectionId) == 0x000000, "Member 'StateProducer_OnDisconnected::ConnectionId' has a wrong offset!");

// Function ccsconn.StateProducer.OnMessageReceived
// 0x0018 (0x0018 - 0x0000)
struct StateProducer_OnMessageReceived final
{
public:
	int32                                         ConnectionId;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<uint8>                                 Message;                                           // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(StateProducer_OnMessageReceived) == 0x000008, "Wrong alignment on StateProducer_OnMessageReceived");
static_assert(sizeof(StateProducer_OnMessageReceived) == 0x000018, "Wrong size on StateProducer_OnMessageReceived");
static_assert(offsetof(StateProducer_OnMessageReceived, ConnectionId) == 0x000000, "Member 'StateProducer_OnMessageReceived::ConnectionId' has a wrong offset!");
static_assert(offsetof(StateProducer_OnMessageReceived, Message) == 0x000008, "Member 'StateProducer_OnMessageReceived::Message' has a wrong offset!");

}

