#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChaGABP_DoLongInteraction

#include "Basic.hpp"

#include "Solarland_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ChaGABP_DoLongInteraction.ChaGABP_DoLongInteraction_C
// 0x0000 (0x0710 - 0x0710)
class UChaGABP_DoLongInteraction_C final : public UChaGA_DoLongInteraction
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ChaGABP_DoLongInteraction_C">();
	}
	static class UChaGABP_DoLongInteraction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChaGABP_DoLongInteraction_C>();
	}
};
static_assert(alignof(UChaGABP_DoLongInteraction_C) == 0x000008, "Wrong alignment on UChaGABP_DoLongInteraction_C");
static_assert(sizeof(UChaGABP_DoLongInteraction_C) == 0x000710, "Wrong size on UChaGABP_DoLongInteraction_C");

}

