#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChaGABP_SlideTackle

#include "Basic.hpp"

#include "Solarland_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ChaGABP_SlideTackle.ChaGABP_SlideTackle_C
// 0x0000 (0x05E8 - 0x05E8)
class UChaGABP_SlideTackle_C final : public UChaGA_SlideTackle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ChaGABP_SlideTackle_C">();
	}
	static class UChaGABP_SlideTackle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChaGABP_SlideTackle_C>();
	}
};
static_assert(alignof(UChaGABP_SlideTackle_C) == 0x000008, "Wrong alignment on UChaGABP_SlideTackle_C");
static_assert(sizeof(UChaGABP_SlideTackle_C) == 0x0005E8, "Wrong size on UChaGABP_SlideTackle_C");

}

