#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChaGCBP_DyingMoveEnh

#include "Basic.hpp"

#include "ChaGCBP_DyingMoveEnh_classes.hpp"
#include "ChaGCBP_DyingMoveEnh_parameters.hpp"


namespace SDK
{

// Function ChaGCBP_DyingMoveEnh.ChaGCBP_DyingMoveEnh_C.ExecuteUbergraph_ChaGCBP_DyingMoveEnh
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChaGCBP_DyingMoveEnh_C::ExecuteUbergraph_ChaGCBP_DyingMoveEnh(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChaGCBP_DyingMoveEnh_C", "ExecuteUbergraph_ChaGCBP_DyingMoveEnh");

	Params::ChaGCBP_DyingMoveEnh_C_ExecuteUbergraph_ChaGCBP_DyingMoveEnh Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ChaGCBP_DyingMoveEnh.ChaGCBP_DyingMoveEnh_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChaGCBP_DyingMoveEnh_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChaGCBP_DyingMoveEnh_C", "ReceiveTick");

	Params::ChaGCBP_DyingMoveEnh_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ChaGCBP_DyingMoveEnh.ChaGCBP_DyingMoveEnh_C.OnRemove
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayCueParameters&    Parameters                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool AChaGCBP_DyingMoveEnh_C::OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChaGCBP_DyingMoveEnh_C", "OnRemove");

	Params::ChaGCBP_DyingMoveEnh_C_OnRemove Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

