#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChaGEBP_DyingMoveSpeedEnh

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ChaGEBP_DyingMoveSpeedEnh.ChaGEBP_DyingMoveSpeedEnh_C
// 0x0000 (0x0898 - 0x0898)
class UChaGEBP_DyingMoveSpeedEnh_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ChaGEBP_DyingMoveSpeedEnh_C">();
	}
	static class UChaGEBP_DyingMoveSpeedEnh_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChaGEBP_DyingMoveSpeedEnh_C>();
	}
};
static_assert(alignof(UChaGEBP_DyingMoveSpeedEnh_C) == 0x000008, "Wrong alignment on UChaGEBP_DyingMoveSpeedEnh_C");
static_assert(sizeof(UChaGEBP_DyingMoveSpeedEnh_C) == 0x000898, "Wrong size on UChaGEBP_DyingMoveSpeedEnh_C");

}

