#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChaGABP_WallRun

#include "Basic.hpp"

#include "Solarland_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ChaGABP_WallRun.ChaGABP_WallRun_C
// 0x0000 (0x0660 - 0x0660)
class UChaGABP_WallRun_C final : public UChaGA_WallRun
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ChaGABP_WallRun_C">();
	}
	static class UChaGABP_WallRun_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChaGABP_WallRun_C>();
	}
};
static_assert(alignof(UChaGABP_WallRun_C) == 0x000008, "Wrong alignment on UChaGABP_WallRun_C");
static_assert(sizeof(UChaGABP_WallRun_C) == 0x000660, "Wrong size on UChaGABP_WallRun_C");

}

