#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChaGCBP_BeauSkillEnhance

#include "Basic.hpp"

#include "Solarland_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ChaGCBP_BeauSkillEnhance.ChaGCBP_BeauSkillEnhance_C
// 0x0000 (0x0060 - 0x0060)
class UChaGCBP_BeauSkillEnhance_C final : public UChaGC_CharacterStaticCueBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ChaGCBP_BeauSkillEnhance_C">();
	}
	static class UChaGCBP_BeauSkillEnhance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChaGCBP_BeauSkillEnhance_C>();
	}
};
static_assert(alignof(UChaGCBP_BeauSkillEnhance_C) == 0x000008, "Wrong alignment on UChaGCBP_BeauSkillEnhance_C");
static_assert(sizeof(UChaGCBP_BeauSkillEnhance_C) == 0x000060, "Wrong size on UChaGCBP_BeauSkillEnhance_C");

}

