#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChaGABP_LeadChargeActivation

#include "Basic.hpp"

#include "ChaGABP_LeadChargeActivation_classes.hpp"
#include "ChaGABP_LeadChargeActivation_parameters.hpp"


namespace SDK
{

// Function ChaGABP_LeadChargeActivation.ChaGABP_LeadChargeActivation_C.OnFinish_3F95AB2141DFDBDFD06CEEAFB1C04DAA
// (BlueprintCallable, BlueprintEvent)

void UChaGABP_LeadChargeActivation_C::OnFinish_3F95AB2141DFDBDFD06CEEAFB1C04DAA()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChaGABP_LeadChargeActivation_C", "OnFinish_3F95AB2141DFDBDFD06CEEAFB1C04DAA");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ChaGABP_LeadChargeActivation.ChaGABP_LeadChargeActivation_C.K2_CommitExecute
// (Event, Public, BlueprintEvent)

void UChaGABP_LeadChargeActivation_C::K2_CommitExecute()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChaGABP_LeadChargeActivation_C", "K2_CommitExecute");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ChaGABP_LeadChargeActivation.ChaGABP_LeadChargeActivation_C.ExecuteUbergraph_ChaGABP_LeadChargeActivation
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UChaGABP_LeadChargeActivation_C::ExecuteUbergraph_ChaGABP_LeadChargeActivation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChaGABP_LeadChargeActivation_C", "ExecuteUbergraph_ChaGABP_LeadChargeActivation");

	Params::ChaGABP_LeadChargeActivation_C_ExecuteUbergraph_ChaGABP_LeadChargeActivation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

