#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Crosshair_Unarm

#include "Basic.hpp"


namespace SDK::Params
{

// Function Crosshair_Unarm.Crosshair_Unarm_C.ExecuteUbergraph_Crosshair_Unarm
// 0x0004 (0x0004 - 0x0000)
struct Crosshair_Unarm_C_ExecuteUbergraph_Crosshair_Unarm final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Crosshair_Unarm_C_ExecuteUbergraph_Crosshair_Unarm) == 0x000004, "Wrong alignment on Crosshair_Unarm_C_ExecuteUbergraph_Crosshair_Unarm");
static_assert(sizeof(Crosshair_Unarm_C_ExecuteUbergraph_Crosshair_Unarm) == 0x000004, "Wrong size on Crosshair_Unarm_C_ExecuteUbergraph_Crosshair_Unarm");
static_assert(offsetof(Crosshair_Unarm_C_ExecuteUbergraph_Crosshair_Unarm, EntryPoint) == 0x000000, "Member 'Crosshair_Unarm_C_ExecuteUbergraph_Crosshair_Unarm::EntryPoint' has a wrong offset!");

}

