#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_Item_Quality

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_Item_Quality.E_Item_Quality
// NumValues: 0x0008
enum class E_Item_Quality : uint8
{
	NewEnumerator6                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator3                           = 4,
	NewEnumerator5                           = 5,
	NewEnumerator4                           = 6,
	E_Item_MAX                               = 7,
};

}

