#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_RedHintPath_New

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_RedHintPath_New.E_RedHintPath_New
// NumValues: 0x003C
enum class E_RedHintPath_New : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	NewEnumerator5                           = 5,
	NewEnumerator6                           = 6,
	NewEnumerator7                           = 7,
	NewEnumerator8                           = 8,
	NewEnumerator9                           = 9,
	NewEnumerator10                          = 10,
	NewEnumerator11                          = 11,
	NewEnumerator12                          = 12,
	NewEnumerator13                          = 13,
	NewEnumerator14                          = 14,
	NewEnumerator15                          = 15,
	NewEnumerator16                          = 16,
	NewEnumerator17                          = 17,
	NewEnumerator18                          = 18,
	NewEnumerator19                          = 19,
	NewEnumerator20                          = 20,
	NewEnumerator21                          = 21,
	NewEnumerator22                          = 22,
	NewEnumerator23                          = 23,
	NewEnumerator24                          = 24,
	NewEnumerator25                          = 25,
	NewEnumerator26                          = 26,
	NewEnumerator27                          = 27,
	NewEnumerator28                          = 28,
	NewEnumerator29                          = 29,
	NewEnumerator30                          = 30,
	NewEnumerator31                          = 31,
	NewEnumerator32                          = 32,
	NewEnumerator33                          = 33,
	NewEnumerator34                          = 34,
	NewEnumerator35                          = 35,
	NewEnumerator36                          = 36,
	NewEnumerator37                          = 37,
	NewEnumerator38                          = 38,
	NewEnumerator39                          = 39,
	NewEnumerator40                          = 40,
	NewEnumerator41                          = 41,
	NewEnumerator42                          = 42,
	NewEnumerator43                          = 43,
	NewEnumerator44                          = 44,
	NewEnumerator45                          = 45,
	NewEnumerator46                          = 46,
	NewEnumerator49                          = 47,
	NewEnumerator50                          = 48,
	NewEnumerator51                          = 49,
	NewEnumerator52                          = 50,
	NewEnumerator53                          = 51,
	NewEnumerator55                          = 52,
	NewEnumerator56                          = 53,
	NewEnumerator57                          = 54,
	NewEnumerator58                          = 55,
	NewEnumerator59                          = 56,
	NewEnumerator60                          = 57,
	NewEnumerator47                          = 58,
	E_RedHintPath_MAX                        = 59,
};

}

