#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FL_ColorUtility

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "E_Item_Quality_structs.hpp"
#include "LobbyQualityStructure_structs.hpp"
#include "S_ColorInfo_structs.hpp"


namespace SDK::Params
{

// Function FL_ColorUtility.FL_ColorUtility_C.GetColor
// 0x0098 (0x0098 - 0x0000)
struct FL_ColorUtility_C_GetColor final
{
public:
	class FName                                   索引;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Color;                                             // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FS_ColorInfo                           CallFunc_GetDataTableRowFromName_OutRow;           // 0x0030(0x0040)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0078(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0088(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(FL_ColorUtility_C_GetColor) == 0x000008, "Wrong alignment on FL_ColorUtility_C_GetColor");
static_assert(sizeof(FL_ColorUtility_C_GetColor) == 0x000098, "Wrong size on FL_ColorUtility_C_GetColor");
static_assert(offsetof(FL_ColorUtility_C_GetColor, 索引) == 0x000000, "Member 'FL_ColorUtility_C_GetColor::索引' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetColor, __WorldContext) == 0x000008, "Member 'FL_ColorUtility_C_GetColor::__WorldContext' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetColor, Color) == 0x000010, "Member 'FL_ColorUtility_C_GetColor::Color' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetColor, CallFunc_Conv_NameToString_ReturnValue) == 0x000020, "Member 'FL_ColorUtility_C_GetColor::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetColor, CallFunc_GetDataTableRowFromName_OutRow) == 0x000030, "Member 'FL_ColorUtility_C_GetColor::CallFunc_GetDataTableRowFromName_OutRow' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetColor, CallFunc_GetDataTableRowFromName_ReturnValue) == 0x000070, "Member 'FL_ColorUtility_C_GetColor::CallFunc_GetDataTableRowFromName_ReturnValue' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetColor, CallFunc_Concat_StrStr_ReturnValue) == 0x000078, "Member 'FL_ColorUtility_C_GetColor::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetColor, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000088, "Member 'FL_ColorUtility_C_GetColor::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");

// Function FL_ColorUtility.FL_ColorUtility_C.GetLobbyQualityColor
// 0x0070 (0x0070 - 0x0000)
struct FL_ColorUtility_C_GetLobbyQualityColor final
{
public:
	E_Item_Quality                                Quilty;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                Widget;                                            // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           TxtColor;                                          // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           FrameColor;                                        // 0x0028(0x0010)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDataAsset*                             CallFunc_GetLobbyQualityDataAsset_ReturnValue;     // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ULobbyQualityDataAsset_C*               K2Node_DynamicCast_AsLobby_Quality_Data_Asset;     // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLobbyQualityStructure                 CallFunc_Map_Find_Value;                           // 0x004C(0x0020)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(FL_ColorUtility_C_GetLobbyQualityColor) == 0x000008, "Wrong alignment on FL_ColorUtility_C_GetLobbyQualityColor");
static_assert(sizeof(FL_ColorUtility_C_GetLobbyQualityColor) == 0x000070, "Wrong size on FL_ColorUtility_C_GetLobbyQualityColor");
static_assert(offsetof(FL_ColorUtility_C_GetLobbyQualityColor, Quilty) == 0x000000, "Member 'FL_ColorUtility_C_GetLobbyQualityColor::Quilty' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetLobbyQualityColor, Widget) == 0x000008, "Member 'FL_ColorUtility_C_GetLobbyQualityColor::Widget' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetLobbyQualityColor, __WorldContext) == 0x000010, "Member 'FL_ColorUtility_C_GetLobbyQualityColor::__WorldContext' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetLobbyQualityColor, TxtColor) == 0x000018, "Member 'FL_ColorUtility_C_GetLobbyQualityColor::TxtColor' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetLobbyQualityColor, FrameColor) == 0x000028, "Member 'FL_ColorUtility_C_GetLobbyQualityColor::FrameColor' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetLobbyQualityColor, CallFunc_GetLobbyQualityDataAsset_ReturnValue) == 0x000038, "Member 'FL_ColorUtility_C_GetLobbyQualityColor::CallFunc_GetLobbyQualityDataAsset_ReturnValue' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetLobbyQualityColor, K2Node_DynamicCast_AsLobby_Quality_Data_Asset) == 0x000040, "Member 'FL_ColorUtility_C_GetLobbyQualityColor::K2Node_DynamicCast_AsLobby_Quality_Data_Asset' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetLobbyQualityColor, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'FL_ColorUtility_C_GetLobbyQualityColor::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetLobbyQualityColor, CallFunc_Map_Find_Value) == 0x00004C, "Member 'FL_ColorUtility_C_GetLobbyQualityColor::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(FL_ColorUtility_C_GetLobbyQualityColor, CallFunc_Map_Find_ReturnValue) == 0x00006C, "Member 'FL_ColorUtility_C_GetLobbyQualityColor::CallFunc_Map_Find_ReturnValue' has a wrong offset!");

}

