#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_SummonTower_New

#include "Basic.hpp"

#include "Solarland_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_SummonTower_New.GA_SummonTower_New_C
// 0x0000 (0x09A0 - 0x09A0)
class UGA_SummonTower_New_C final : public UChaGA_SummonTower_New
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_SummonTower_New_C">();
	}
	static class UGA_SummonTower_New_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_SummonTower_New_C>();
	}
};
static_assert(alignof(UGA_SummonTower_New_C) == 0x000010, "Wrong alignment on UGA_SummonTower_New_C");
static_assert(sizeof(UGA_SummonTower_New_C) == 0x0009A0, "Wrong size on UGA_SummonTower_New_C");

}

