#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_SuperRadarChoose

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function GC_SuperRadarChoose.GC_SuperRadarChoose_C.OnActive
// 0x0110 (0x0110 - 0x0000)
struct GC_SuperRadarChoose_C_OnActive final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00D0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x00D8(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASolarCharacter*                        K2Node_DynamicCast_AsSolar_Character;              // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E9[0x3];                                       // 0x00E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x00EC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue;          // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F9[0x3];                                       // 0x00F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_PostEventAtLocation_ReturnValue;          // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue;                  // 0x0100(0x0008)(NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_PostEventAtLocation_ReturnValue_1;        // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_SuperRadarChoose_C_OnActive) == 0x000008, "Wrong alignment on GC_SuperRadarChoose_C_OnActive");
static_assert(sizeof(GC_SuperRadarChoose_C_OnActive) == 0x000110, "Wrong size on GC_SuperRadarChoose_C_OnActive");
static_assert(offsetof(GC_SuperRadarChoose_C_OnActive, MyTarget) == 0x000000, "Member 'GC_SuperRadarChoose_C_OnActive::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_SuperRadarChoose_C_OnActive, Parameters) == 0x000008, "Member 'GC_SuperRadarChoose_C_OnActive::Parameters' has a wrong offset!");
static_assert(offsetof(GC_SuperRadarChoose_C_OnActive, ReturnValue) == 0x0000D8, "Member 'GC_SuperRadarChoose_C_OnActive::ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_SuperRadarChoose_C_OnActive, K2Node_DynamicCast_AsSolar_Character) == 0x0000E0, "Member 'GC_SuperRadarChoose_C_OnActive::K2Node_DynamicCast_AsSolar_Character' has a wrong offset!");
static_assert(offsetof(GC_SuperRadarChoose_C_OnActive, K2Node_DynamicCast_bSuccess) == 0x0000E8, "Member 'GC_SuperRadarChoose_C_OnActive::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GC_SuperRadarChoose_C_OnActive, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0000EC, "Member 'GC_SuperRadarChoose_C_OnActive::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_SuperRadarChoose_C_OnActive, CallFunc_IsLocallyControlled_ReturnValue) == 0x0000F8, "Member 'GC_SuperRadarChoose_C_OnActive::CallFunc_IsLocallyControlled_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_SuperRadarChoose_C_OnActive, CallFunc_PostEventAtLocation_ReturnValue) == 0x0000FC, "Member 'GC_SuperRadarChoose_C_OnActive::CallFunc_PostEventAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_SuperRadarChoose_C_OnActive, CallFunc_K2_SetTimer_ReturnValue) == 0x000100, "Member 'GC_SuperRadarChoose_C_OnActive::CallFunc_K2_SetTimer_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_SuperRadarChoose_C_OnActive, CallFunc_PostEventAtLocation_ReturnValue_1) == 0x000108, "Member 'GC_SuperRadarChoose_C_OnActive::CallFunc_PostEventAtLocation_ReturnValue_1' has a wrong offset!");

// Function GC_SuperRadarChoose.GC_SuperRadarChoose_C.OnRemove
// 0x00E0 (0x00E0 - 0x0000)
struct GC_SuperRadarChoose_C_OnRemove final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00D0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x00D8(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GC_SuperRadarChoose_C_OnRemove) == 0x000008, "Wrong alignment on GC_SuperRadarChoose_C_OnRemove");
static_assert(sizeof(GC_SuperRadarChoose_C_OnRemove) == 0x0000E0, "Wrong size on GC_SuperRadarChoose_C_OnRemove");
static_assert(offsetof(GC_SuperRadarChoose_C_OnRemove, MyTarget) == 0x000000, "Member 'GC_SuperRadarChoose_C_OnRemove::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_SuperRadarChoose_C_OnRemove, Parameters) == 0x000008, "Member 'GC_SuperRadarChoose_C_OnRemove::Parameters' has a wrong offset!");
static_assert(offsetof(GC_SuperRadarChoose_C_OnRemove, ReturnValue) == 0x0000D8, "Member 'GC_SuperRadarChoose_C_OnRemove::ReturnValue' has a wrong offset!");

// Function GC_SuperRadarChoose.GC_SuperRadarChoose_C.PlayPlayerEffect
// 0x0008 (0x0008 - 0x0000)
struct GC_SuperRadarChoose_C_PlayPlayerEffect final
{
public:
	int32                                         CallFunc_StartActorEffect_ReturnValue;             // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_StartActorEffect_ReturnValue_1;           // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_SuperRadarChoose_C_PlayPlayerEffect) == 0x000004, "Wrong alignment on GC_SuperRadarChoose_C_PlayPlayerEffect");
static_assert(sizeof(GC_SuperRadarChoose_C_PlayPlayerEffect) == 0x000008, "Wrong size on GC_SuperRadarChoose_C_PlayPlayerEffect");
static_assert(offsetof(GC_SuperRadarChoose_C_PlayPlayerEffect, CallFunc_StartActorEffect_ReturnValue) == 0x000000, "Member 'GC_SuperRadarChoose_C_PlayPlayerEffect::CallFunc_StartActorEffect_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_SuperRadarChoose_C_PlayPlayerEffect, CallFunc_StartActorEffect_ReturnValue_1) == 0x000004, "Member 'GC_SuperRadarChoose_C_PlayPlayerEffect::CallFunc_StartActorEffect_ReturnValue_1' has a wrong offset!");

}

