#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Vehicle_Weapon_Burning

#include "Basic.hpp"

#include "Solarland_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Vehicle_Weapon_Burning.GC_Vehicle_Weapon_Burning_C
// 0x0008 (0x03B0 - 0x03A8)
class AGC_Vehicle_Weapon_Burning_C final : public ASolarVehicleGC_Burning
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Vehicle_Weapon_Burning_C">();
	}
	static class AGC_Vehicle_Weapon_Burning_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Vehicle_Weapon_Burning_C>();
	}
};
static_assert(alignof(AGC_Vehicle_Weapon_Burning_C) == 0x000008, "Wrong alignment on AGC_Vehicle_Weapon_Burning_C");
static_assert(sizeof(AGC_Vehicle_Weapon_Burning_C) == 0x0003B0, "Wrong size on AGC_Vehicle_Weapon_Burning_C");
static_assert(offsetof(AGC_Vehicle_Weapon_Burning_C, DefaultSceneRoot) == 0x0003A8, "Member 'AGC_Vehicle_Weapon_Burning_C::DefaultSceneRoot' has a wrong offset!");

}

