#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MMCBP_SuperSkillCD

#include "Basic.hpp"

#include "Solarland_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MMCBP_SuperSkillCD.MMCBP_SuperSkillCD_C
// 0x0000 (0x0040 - 0x0040)
class UMMCBP_SuperSkillCD_C final : public UMMC_GenericCooldown
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MMCBP_SuperSkillCD_C">();
	}
	static class UMMCBP_SuperSkillCD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMMCBP_SuperSkillCD_C>();
	}
};
static_assert(alignof(UMMCBP_SuperSkillCD_C) == 0x000008, "Wrong alignment on UMMCBP_SuperSkillCD_C");
static_assert(sizeof(UMMCBP_SuperSkillCD_C) == 0x000040, "Wrong size on UMMCBP_SuperSkillCD_C");

}

