#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OverlayABP_Skill_YJ

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function OverlayABP_Skill_YJ.OverlayABP_Skill_YJ_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct OverlayABP_Skill_YJ_C_AnimGraph final
{
public:
	struct FPoseLink                              bpp__AnimGraph__pf;                                // 0x0000(0x0010)(Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(OverlayABP_Skill_YJ_C_AnimGraph) == 0x000008, "Wrong alignment on OverlayABP_Skill_YJ_C_AnimGraph");
static_assert(sizeof(OverlayABP_Skill_YJ_C_AnimGraph) == 0x000010, "Wrong size on OverlayABP_Skill_YJ_C_AnimGraph");
static_assert(offsetof(OverlayABP_Skill_YJ_C_AnimGraph, bpp__AnimGraph__pf) == 0x000000, "Member 'OverlayABP_Skill_YJ_C_AnimGraph::bpp__AnimGraph__pf' has a wrong offset!");

// Function OverlayABP_Skill_YJ.OverlayABP_Skill_YJ_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct OverlayABP_Skill_YJ_C_BlueprintUpdateAnimation final
{
public:
	float                                         bpp__DeltaTimeX__pf;                               // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(OverlayABP_Skill_YJ_C_BlueprintUpdateAnimation) == 0x000004, "Wrong alignment on OverlayABP_Skill_YJ_C_BlueprintUpdateAnimation");
static_assert(sizeof(OverlayABP_Skill_YJ_C_BlueprintUpdateAnimation) == 0x000004, "Wrong size on OverlayABP_Skill_YJ_C_BlueprintUpdateAnimation");
static_assert(offsetof(OverlayABP_Skill_YJ_C_BlueprintUpdateAnimation, bpp__DeltaTimeX__pf) == 0x000000, "Member 'OverlayABP_Skill_YJ_C_BlueprintUpdateAnimation::bpp__DeltaTimeX__pf' has a wrong offset!");

// Function OverlayABP_Skill_YJ.OverlayABP_Skill_YJ_C.OverlaySkillAnimationLayer
// 0x0020 (0x0020 - 0x0000)
struct OverlayABP_Skill_YJ_C_OverlaySkillAnimationLayer final
{
public:
	struct FPoseLink                              bpp__BasePose__pf;                                 // 0x0000(0x0010)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	struct FPoseLink                              bpp__OverlaySkillAnimationLayer__pf;               // 0x0010(0x0010)(Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(OverlayABP_Skill_YJ_C_OverlaySkillAnimationLayer) == 0x000008, "Wrong alignment on OverlayABP_Skill_YJ_C_OverlaySkillAnimationLayer");
static_assert(sizeof(OverlayABP_Skill_YJ_C_OverlaySkillAnimationLayer) == 0x000020, "Wrong size on OverlayABP_Skill_YJ_C_OverlaySkillAnimationLayer");
static_assert(offsetof(OverlayABP_Skill_YJ_C_OverlaySkillAnimationLayer, bpp__BasePose__pf) == 0x000000, "Member 'OverlayABP_Skill_YJ_C_OverlaySkillAnimationLayer::bpp__BasePose__pf' has a wrong offset!");
static_assert(offsetof(OverlayABP_Skill_YJ_C_OverlaySkillAnimationLayer, bpp__OverlaySkillAnimationLayer__pf) == 0x000010, "Member 'OverlayABP_Skill_YJ_C_OverlaySkillAnimationLayer::bpp__OverlaySkillAnimationLayer__pf' has a wrong offset!");

}

