#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpecABP_Skill_TrapMineThrow

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "Solarland_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass SpecABP_Skill_TrapMineThrow.SpecABP_Skill_TrapMineThrow_C
// 0x09A0 (0x0D10 - 0x0370)
class USpecABP_Skill_TrapMineThrow_C final : public USolarSpecABP_Skill
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x0378(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x03A8(0x0078)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x0420(0x00C0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x04E0(0x0028)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_3;                  // 0x0508(0x00C8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x05D0(0x0088)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x0658(0x0028)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_2;                  // 0x0680(0x00C8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x0748(0x0088)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace;            // 0x07D0(0x01A0)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_1;                  // 0x0970(0x00C8)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x0A38(0x00C8)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x0B00(0x00D0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x0BD0(0x0088)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0C58(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0CE0(0x0030)()

public:
	void ExecuteUbergraph_SpecABP_Skill_TrapMineThrow(int32 EntryPoint);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_SpecABP_Skill_TrapMineThrow_AnimGraphNode_TwoWayBlend_8144F64340436B8B5CE6B7B1AD67FED7();
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void SkillAnimationLayer(const struct FPoseLink& BasePose, struct FPoseLink* SkillAnimationLayer_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SpecABP_Skill_TrapMineThrow_C">();
	}
	static class USpecABP_Skill_TrapMineThrow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USpecABP_Skill_TrapMineThrow_C>();
	}
};
static_assert(alignof(USpecABP_Skill_TrapMineThrow_C) == 0x000010, "Wrong alignment on USpecABP_Skill_TrapMineThrow_C");
static_assert(sizeof(USpecABP_Skill_TrapMineThrow_C) == 0x000D10, "Wrong size on USpecABP_Skill_TrapMineThrow_C");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, UberGraphFrame) == 0x000370, "Member 'USpecABP_Skill_TrapMineThrow_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_Root_1) == 0x000378, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_Root_1' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_LinkedInputPose) == 0x0003A8, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_SaveCachedPose) == 0x000420, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_UseCachedPose_1) == 0x0004E0, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_LayeredBoneBlend_3) == 0x000508, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_LayeredBoneBlend_3' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_SequencePlayer_3) == 0x0005D0, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_UseCachedPose) == 0x000658, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_LayeredBoneBlend_2) == 0x000680, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_LayeredBoneBlend_2' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_SequencePlayer_2) == 0x000748, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_RotationOffsetBlendSpace) == 0x0007D0, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_RotationOffsetBlendSpace' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_LayeredBoneBlend_1) == 0x000970, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_LayeredBoneBlend_1' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_LayeredBoneBlend) == 0x000A38, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_LayeredBoneBlend' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_TwoWayBlend) == 0x000B00, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_TwoWayBlend' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_SequencePlayer_1) == 0x000BD0, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_SequencePlayer) == 0x000C58, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(USpecABP_Skill_TrapMineThrow_C, AnimGraphNode_Root) == 0x000CE0, "Member 'USpecABP_Skill_TrapMineThrow_C::AnimGraphNode_Root' has a wrong offset!");

}

