#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_AudioDebugEditableText

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Solarland_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_AudioDebugEditableText.UI_AudioDebugEditableText_C
// 0x0030 (0x0620 - 0x05F0)
class UUI_AudioDebugEditableText_C final : public USolarUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UEditableText*                          EditableText_28;                                   // 0x05F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 ConsoleCommand;                                    // 0x0600(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 EmitterName;                                       // 0x0610(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_AudioDebugEditableText(int32 EntryPoint);
	void BndEvt__EditableText_28_K2Node_ComponentBoundEvent_0_OnEditableTextCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod);
	void OnNameChanged(const class FString& Name_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_AudioDebugEditableText_C">();
	}
	static class UUI_AudioDebugEditableText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_AudioDebugEditableText_C>();
	}
};
static_assert(alignof(UUI_AudioDebugEditableText_C) == 0x000008, "Wrong alignment on UUI_AudioDebugEditableText_C");
static_assert(sizeof(UUI_AudioDebugEditableText_C) == 0x000620, "Wrong size on UUI_AudioDebugEditableText_C");
static_assert(offsetof(UUI_AudioDebugEditableText_C, UberGraphFrame) == 0x0005F0, "Member 'UUI_AudioDebugEditableText_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_AudioDebugEditableText_C, EditableText_28) == 0x0005F8, "Member 'UUI_AudioDebugEditableText_C::EditableText_28' has a wrong offset!");
static_assert(offsetof(UUI_AudioDebugEditableText_C, ConsoleCommand) == 0x000600, "Member 'UUI_AudioDebugEditableText_C::ConsoleCommand' has a wrong offset!");
static_assert(offsetof(UUI_AudioDebugEditableText_C, EmitterName) == 0x000610, "Member 'UUI_AudioDebugEditableText_C::EmitterName' has a wrong offset!");

}

