#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Component_Hover_Square_0px

#include "Basic.hpp"

#include "InputCore_structs.hpp"
#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "SolarUI_structs.hpp"


namespace SDK::Params
{

// Function UI_Component_Hover_Square_0px.UI_Component_Hover_Square_0px_C.ConstructSetHover
// 0x0005 (0x0005 - 0x0000)
struct UI_Component_Hover_Square_0px_C_ConstructSetHover final
{
public:
	bool                                          IsHovered_0;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Component_Hover_Square_0px_C_ConstructSetHover) == 0x000001, "Wrong alignment on UI_Component_Hover_Square_0px_C_ConstructSetHover");
static_assert(sizeof(UI_Component_Hover_Square_0px_C_ConstructSetHover) == 0x000005, "Wrong size on UI_Component_Hover_Square_0px_C_ConstructSetHover");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ConstructSetHover, IsHovered_0) == 0x000000, "Member 'UI_Component_Hover_Square_0px_C_ConstructSetHover::IsHovered_0' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ConstructSetHover, Temp_bool_Variable) == 0x000001, "Member 'UI_Component_Hover_Square_0px_C_ConstructSetHover::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ConstructSetHover, Temp_byte_Variable) == 0x000002, "Member 'UI_Component_Hover_Square_0px_C_ConstructSetHover::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ConstructSetHover, Temp_byte_Variable_1) == 0x000003, "Member 'UI_Component_Hover_Square_0px_C_ConstructSetHover::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ConstructSetHover, K2Node_Select_Default) == 0x000004, "Member 'UI_Component_Hover_Square_0px_C_ConstructSetHover::K2Node_Select_Default' has a wrong offset!");

// Function UI_Component_Hover_Square_0px.UI_Component_Hover_Square_0px_C.SetOpen
// 0x0002 (0x0002 - 0x0000)
struct UI_Component_Hover_Square_0px_C_SetOpen final
{
public:
	bool                                          bOpen;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Component_Hover_Square_0px_C_SetOpen) == 0x000001, "Wrong alignment on UI_Component_Hover_Square_0px_C_SetOpen");
static_assert(sizeof(UI_Component_Hover_Square_0px_C_SetOpen) == 0x000002, "Wrong size on UI_Component_Hover_Square_0px_C_SetOpen");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_SetOpen, bOpen) == 0x000000, "Member 'UI_Component_Hover_Square_0px_C_SetOpen::bOpen' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_SetOpen, CallFunc_Not_PreBool_ReturnValue) == 0x000001, "Member 'UI_Component_Hover_Square_0px_C_SetOpen::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");

// Function UI_Component_Hover_Square_0px.UI_Component_Hover_Square_0px_C.SetSizeToContent
// 0x0010 (0x0010 - 0x0000)
struct UI_Component_Hover_Square_0px_C_SetSizeToContent final
{
public:
	bool                                          SizeToContent_0;                                   // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCanvasPanelSlot*                       CallFunc_SlotAsCanvasSlot_ReturnValue;             // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Component_Hover_Square_0px_C_SetSizeToContent) == 0x000008, "Wrong alignment on UI_Component_Hover_Square_0px_C_SetSizeToContent");
static_assert(sizeof(UI_Component_Hover_Square_0px_C_SetSizeToContent) == 0x000010, "Wrong size on UI_Component_Hover_Square_0px_C_SetSizeToContent");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_SetSizeToContent, SizeToContent_0) == 0x000000, "Member 'UI_Component_Hover_Square_0px_C_SetSizeToContent::SizeToContent_0' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_SetSizeToContent, CallFunc_SlotAsCanvasSlot_ReturnValue) == 0x000008, "Member 'UI_Component_Hover_Square_0px_C_SetSizeToContent::CallFunc_SlotAsCanvasSlot_ReturnValue' has a wrong offset!");

// Function UI_Component_Hover_Square_0px.UI_Component_Hover_Square_0px_C.SetSelect
// 0x0001 (0x0001 - 0x0000)
struct UI_Component_Hover_Square_0px_C_SetSelect final
{
public:
	bool                                          Select_0;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Component_Hover_Square_0px_C_SetSelect) == 0x000001, "Wrong alignment on UI_Component_Hover_Square_0px_C_SetSelect");
static_assert(sizeof(UI_Component_Hover_Square_0px_C_SetSelect) == 0x000001, "Wrong size on UI_Component_Hover_Square_0px_C_SetSelect");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_SetSelect, Select_0) == 0x000000, "Member 'UI_Component_Hover_Square_0px_C_SetSelect::Select_0' has a wrong offset!");

// Function UI_Component_Hover_Square_0px.UI_Component_Hover_Square_0px_C.SetHover
// 0x0020 (0x0020 - 0x0000)
struct UI_Component_Hover_Square_0px_C_SetHover final
{
public:
	bool                                          Hover_0;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue;         // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Component_Hover_Square_0px_C_SetHover) == 0x000008, "Wrong alignment on UI_Component_Hover_Square_0px_C_SetHover");
static_assert(sizeof(UI_Component_Hover_Square_0px_C_SetHover) == 0x000020, "Wrong size on UI_Component_Hover_Square_0px_C_SetHover");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_SetHover, Hover_0) == 0x000000, "Member 'UI_Component_Hover_Square_0px_C_SetHover::Hover_0' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_SetHover, Temp_bool_Variable) == 0x000001, "Member 'UI_Component_Hover_Square_0px_C_SetHover::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_SetHover, Temp_byte_Variable) == 0x000002, "Member 'UI_Component_Hover_Square_0px_C_SetHover::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_SetHover, Temp_byte_Variable_1) == 0x000003, "Member 'UI_Component_Hover_Square_0px_C_SetHover::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_SetHover, CallFunc_PlayAnimationReverse_ReturnValue) == 0x000008, "Member 'UI_Component_Hover_Square_0px_C_SetHover::CallFunc_PlayAnimationReverse_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_SetHover, K2Node_Select_Default) == 0x000010, "Member 'UI_Component_Hover_Square_0px_C_SetHover::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_SetHover, CallFunc_PlayAnimationForward_ReturnValue) == 0x000018, "Member 'UI_Component_Hover_Square_0px_C_SetHover::CallFunc_PlayAnimationForward_ReturnValue' has a wrong offset!");

// Function UI_Component_Hover_Square_0px.UI_Component_Hover_Square_0px_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Component_Hover_Square_0px_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Component_Hover_Square_0px_C_PreConstruct) == 0x000001, "Wrong alignment on UI_Component_Hover_Square_0px_C_PreConstruct");
static_assert(sizeof(UI_Component_Hover_Square_0px_C_PreConstruct) == 0x000001, "Wrong size on UI_Component_Hover_Square_0px_C_PreConstruct");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_Component_Hover_Square_0px_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_Component_Hover_Square_0px.UI_Component_Hover_Square_0px_C.OnMouseEnter
// 0x00A8 (0x00A8 - 0x0000)
struct UI_Component_Hover_Square_0px_C_OnMouseEnter final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FPointerEvent                          MouseEvent;                                        // 0x0038(0x0070)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(UI_Component_Hover_Square_0px_C_OnMouseEnter) == 0x000008, "Wrong alignment on UI_Component_Hover_Square_0px_C_OnMouseEnter");
static_assert(sizeof(UI_Component_Hover_Square_0px_C_OnMouseEnter) == 0x0000A8, "Wrong size on UI_Component_Hover_Square_0px_C_OnMouseEnter");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_OnMouseEnter, MyGeometry) == 0x000000, "Member 'UI_Component_Hover_Square_0px_C_OnMouseEnter::MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_OnMouseEnter, MouseEvent) == 0x000038, "Member 'UI_Component_Hover_Square_0px_C_OnMouseEnter::MouseEvent' has a wrong offset!");

// Function UI_Component_Hover_Square_0px.UI_Component_Hover_Square_0px_C.OnMouseLeave
// 0x0070 (0x0070 - 0x0000)
struct UI_Component_Hover_Square_0px_C_OnMouseLeave final
{
public:
	struct FPointerEvent                          MouseEvent;                                        // 0x0000(0x0070)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(UI_Component_Hover_Square_0px_C_OnMouseLeave) == 0x000008, "Wrong alignment on UI_Component_Hover_Square_0px_C_OnMouseLeave");
static_assert(sizeof(UI_Component_Hover_Square_0px_C_OnMouseLeave) == 0x000070, "Wrong size on UI_Component_Hover_Square_0px_C_OnMouseLeave");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_OnMouseLeave, MouseEvent) == 0x000000, "Member 'UI_Component_Hover_Square_0px_C_OnMouseLeave::MouseEvent' has a wrong offset!");

// Function UI_Component_Hover_Square_0px.UI_Component_Hover_Square_0px_C.ReceivePlatformLayout
// 0x0001 (0x0001 - 0x0000)
struct UI_Component_Hover_Square_0px_C_ReceivePlatformLayout final
{
public:
	EUSolarWidgetLayoutType                       InLayoutType;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Component_Hover_Square_0px_C_ReceivePlatformLayout) == 0x000001, "Wrong alignment on UI_Component_Hover_Square_0px_C_ReceivePlatformLayout");
static_assert(sizeof(UI_Component_Hover_Square_0px_C_ReceivePlatformLayout) == 0x000001, "Wrong size on UI_Component_Hover_Square_0px_C_ReceivePlatformLayout");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ReceivePlatformLayout, InLayoutType) == 0x000000, "Member 'UI_Component_Hover_Square_0px_C_ReceivePlatformLayout::InLayoutType' has a wrong offset!");

// Function UI_Component_Hover_Square_0px.UI_Component_Hover_Square_0px_C.ExecuteUbergraph_UI_Component_Hover_Square_0px
// 0x0500 (0x0500 - 0x0000)
struct UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0008(0x0038)(IsPlainOldData, NoDestructor)
	struct FPointerEvent                          K2Node_Event_MouseEvent_1;                         // 0x0040(0x0070)(ConstParm)
	struct FPointerEvent                          K2Node_Event_MouseEvent;                           // 0x00B0(0x0070)(ConstParm)
	struct FKey                                   CallFunc_PointerEvent_GetEffectingButton_ReturnValue; // 0x0120(0x0018)(HasGetValueTypeHash)
	struct FVector2D                              CallFunc_PointerEvent_GetCursorDelta_ReturnValue;  // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Key_IsValid_ReturnValue;                  // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsNearlyZero2D_ReturnValue;               // 0x0141(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0142(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0143(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPCPlatform_IsPCPlatform;                // 0x0144(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPCPlatform_IsPCPlatform_1;              // 0x0145(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_146[0x2];                                      // 0x0146(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetEventNameByKey_ReturnValue;            // 0x0148(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_PlaySound2Dbyname_ReturnValue;            // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15C[0x4];                                      // 0x015C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetEventNameByKey_ReturnValue_1;          // 0x0160(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_PlaySound2Dbyname_ReturnValue_1;          // 0x0170(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EUSolarWidgetLayoutType                       K2Node_Event_InLayoutType;                         // 0x0174(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0175(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_176[0xA];                                      // 0x0176(0x000A)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrushOutlineSettings             CallFunc_GetOutlineSettings_ReturnValue;           // 0x0180(0x0040)()
	struct FSlateBrushOutlineSettings             K2Node_MakeStruct_SlateBrushOutlineSettings;       // 0x01C0(0x0040)()
	struct FSlateBrushOutlineSettings             CallFunc_GetOutlineSettings_ReturnValue_1;         // 0x0200(0x0040)()
	struct FSlateBrushOutlineSettings             K2Node_MakeStruct_SlateBrushOutlineSettings_1;     // 0x0240(0x0040)()
	struct FSlateBrushOutlineSettings             CallFunc_GetOutlineSettings_ReturnValue_2;         // 0x0280(0x0040)()
	struct FSlateBrushOutlineSettings             CallFunc_GetOutlineSettings_ReturnValue_3;         // 0x02C0(0x0040)()
	struct FSlateBrushOutlineSettings             K2Node_MakeStruct_SlateBrushOutlineSettings_2;     // 0x0300(0x0040)()
	struct FSlateBrushOutlineSettings             K2Node_MakeStruct_SlateBrushOutlineSettings_3;     // 0x0340(0x0040)()
	struct FSlateBrushOutlineSettings             CallFunc_GetOutlineSettings_ReturnValue_4;         // 0x0380(0x0040)()
	struct FLinearColor                           CallFunc_Subtract_LinearColorLinearColor_ReturnValue; // 0x03C0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x03D0(0x0028)()
	uint8                                         Pad_3F8[0x8];                                      // 0x03F8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrushOutlineSettings             K2Node_MakeStruct_SlateBrushOutlineSettings_4;     // 0x0400(0x0040)()
	struct FSlateBrushOutlineSettings             CallFunc_GetOutlineSettings_ReturnValue_5;         // 0x0440(0x0040)()
	struct FLinearColor                           CallFunc_Subtract_LinearColorLinearColor_ReturnValue_1; // 0x0480(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0490(0x0028)()
	uint8                                         Pad_4B8[0x8];                                      // 0x04B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrushOutlineSettings             K2Node_MakeStruct_SlateBrushOutlineSettings_5;     // 0x04C0(0x0040)()
};
static_assert(alignof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px) == 0x000010, "Wrong alignment on UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px");
static_assert(sizeof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px) == 0x000500, "Wrong size on UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, EntryPoint) == 0x000000, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_Event_IsDesignTime) == 0x000004, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_Event_MyGeometry) == 0x000008, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_Event_MouseEvent_1) == 0x000040, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_Event_MouseEvent_1' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_Event_MouseEvent) == 0x0000B0, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_Event_MouseEvent' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_PointerEvent_GetEffectingButton_ReturnValue) == 0x000120, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_PointerEvent_GetEffectingButton_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_PointerEvent_GetCursorDelta_ReturnValue) == 0x000138, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_PointerEvent_GetCursorDelta_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_Key_IsValid_ReturnValue) == 0x000140, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_Key_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_IsNearlyZero2D_ReturnValue) == 0x000141, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_IsNearlyZero2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_BooleanAND_ReturnValue) == 0x000142, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_Not_PreBool_ReturnValue) == 0x000143, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_IsPCPlatform_IsPCPlatform) == 0x000144, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_IsPCPlatform_IsPCPlatform' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_IsPCPlatform_IsPCPlatform_1) == 0x000145, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_IsPCPlatform_IsPCPlatform_1' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_GetEventNameByKey_ReturnValue) == 0x000148, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_GetEventNameByKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_PlaySound2Dbyname_ReturnValue) == 0x000158, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_PlaySound2Dbyname_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_GetEventNameByKey_ReturnValue_1) == 0x000160, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_GetEventNameByKey_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_PlaySound2Dbyname_ReturnValue_1) == 0x000170, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_PlaySound2Dbyname_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_Event_InLayoutType) == 0x000174, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_Event_InLayoutType' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_SwitchEnum_CmpSuccess) == 0x000175, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_GetOutlineSettings_ReturnValue) == 0x000180, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_GetOutlineSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_MakeStruct_SlateBrushOutlineSettings) == 0x0001C0, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_MakeStruct_SlateBrushOutlineSettings' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_GetOutlineSettings_ReturnValue_1) == 0x000200, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_GetOutlineSettings_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_MakeStruct_SlateBrushOutlineSettings_1) == 0x000240, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_MakeStruct_SlateBrushOutlineSettings_1' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_GetOutlineSettings_ReturnValue_2) == 0x000280, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_GetOutlineSettings_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_GetOutlineSettings_ReturnValue_3) == 0x0002C0, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_GetOutlineSettings_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_MakeStruct_SlateBrushOutlineSettings_2) == 0x000300, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_MakeStruct_SlateBrushOutlineSettings_2' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_MakeStruct_SlateBrushOutlineSettings_3) == 0x000340, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_MakeStruct_SlateBrushOutlineSettings_3' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_GetOutlineSettings_ReturnValue_4) == 0x000380, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_GetOutlineSettings_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_Subtract_LinearColorLinearColor_ReturnValue) == 0x0003C0, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_Subtract_LinearColorLinearColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_MakeStruct_SlateColor) == 0x0003D0, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_MakeStruct_SlateBrushOutlineSettings_4) == 0x000400, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_MakeStruct_SlateBrushOutlineSettings_4' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_GetOutlineSettings_ReturnValue_5) == 0x000440, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_GetOutlineSettings_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, CallFunc_Subtract_LinearColorLinearColor_ReturnValue_1) == 0x000480, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::CallFunc_Subtract_LinearColorLinearColor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_MakeStruct_SlateColor_1) == 0x000490, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");
static_assert(offsetof(UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px, K2Node_MakeStruct_SlateBrushOutlineSettings_5) == 0x0004C0, "Member 'UI_Component_Hover_Square_0px_C_ExecuteUbergraph_UI_Component_Hover_Square_0px::K2Node_MakeStruct_SlateBrushOutlineSettings_5' has a wrong offset!");

}

