#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Component_HorizontalTab_First_Slot_Desktop

#include "Basic.hpp"

#include "E_Type_State_Button_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function UI_Component_HorizontalTab_First_Slot_Desktop.UI_Component_HorizontalTab_First_Slot_Desktop_C.ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop
// 0x0020 (0x0020 - 0x0000)
struct UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	E_Type_State_Button                           Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_Type_State_Button                           Temp_byte_Variable_1;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	E_Type_State_Button                           Temp_byte_Variable_2;                              // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_Type_State_Button                           Temp_byte_Variable_3;                              // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bSelected;                            // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	E_Type_State_Button                           K2Node_Select_Default;                             // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsChecked_ReturnValue;                    // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsChecked_ReturnValue_1;                  // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	E_Type_State_Button                           K2Node_Select_Default_1;                           // 0x000E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x000F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UObject*                                K2Node_Event_ListItemObject;                       // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsSelected;                          // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bIsExpanded;                          // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop) == 0x000008, "Wrong alignment on UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop");
static_assert(sizeof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop) == 0x000020, "Wrong size on UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, EntryPoint) == 0x000000, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, Temp_bool_Variable) == 0x000004, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, Temp_byte_Variable) == 0x000005, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, Temp_byte_Variable_1) == 0x000006, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, Temp_bool_Variable_1) == 0x000007, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, Temp_byte_Variable_2) == 0x000008, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, Temp_byte_Variable_3) == 0x000009, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, K2Node_Event_bSelected) == 0x00000A, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::K2Node_Event_bSelected' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, K2Node_Select_Default) == 0x00000B, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, CallFunc_IsChecked_ReturnValue) == 0x00000C, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::CallFunc_IsChecked_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, CallFunc_IsChecked_ReturnValue_1) == 0x00000D, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::CallFunc_IsChecked_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, K2Node_Select_Default_1) == 0x00000E, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, K2Node_Event_IsDesignTime) == 0x00000F, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, K2Node_Event_ListItemObject) == 0x000010, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::K2Node_Event_ListItemObject' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, K2Node_Event_bIsSelected) == 0x000018, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::K2Node_Event_bIsSelected' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop, K2Node_Event_bIsExpanded) == 0x000019, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_ExecuteUbergraph_UI_Component_HorizontalTab_First_Slot_Desktop::K2Node_Event_bIsExpanded' has a wrong offset!");

// Function UI_Component_HorizontalTab_First_Slot_Desktop.UI_Component_HorizontalTab_First_Slot_Desktop_C.BP_OnItemExpansionChanged
// 0x0001 (0x0001 - 0x0000)
struct UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemExpansionChanged final
{
public:
	bool                                          bIsExpanded;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemExpansionChanged) == 0x000001, "Wrong alignment on UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemExpansionChanged");
static_assert(sizeof(UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemExpansionChanged) == 0x000001, "Wrong size on UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemExpansionChanged");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemExpansionChanged, bIsExpanded) == 0x000000, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemExpansionChanged::bIsExpanded' has a wrong offset!");

// Function UI_Component_HorizontalTab_First_Slot_Desktop.UI_Component_HorizontalTab_First_Slot_Desktop_C.BP_OnItemSelectionChanged
// 0x0001 (0x0001 - 0x0000)
struct UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemSelectionChanged final
{
public:
	bool                                          bIsSelected;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemSelectionChanged) == 0x000001, "Wrong alignment on UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemSelectionChanged");
static_assert(sizeof(UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemSelectionChanged) == 0x000001, "Wrong size on UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemSelectionChanged");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemSelectionChanged, bIsSelected) == 0x000000, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_OnItemSelectionChanged::bIsSelected' has a wrong offset!");

// Function UI_Component_HorizontalTab_First_Slot_Desktop.UI_Component_HorizontalTab_First_Slot_Desktop_C.OnListItemObjectSet
// 0x0008 (0x0008 - 0x0000)
struct UI_Component_HorizontalTab_First_Slot_Desktop_C_OnListItemObjectSet final
{
public:
	class UObject*                                ListItemObject;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Component_HorizontalTab_First_Slot_Desktop_C_OnListItemObjectSet) == 0x000008, "Wrong alignment on UI_Component_HorizontalTab_First_Slot_Desktop_C_OnListItemObjectSet");
static_assert(sizeof(UI_Component_HorizontalTab_First_Slot_Desktop_C_OnListItemObjectSet) == 0x000008, "Wrong size on UI_Component_HorizontalTab_First_Slot_Desktop_C_OnListItemObjectSet");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_OnListItemObjectSet, ListItemObject) == 0x000000, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_OnListItemObjectSet::ListItemObject' has a wrong offset!");

// Function UI_Component_HorizontalTab_First_Slot_Desktop.UI_Component_HorizontalTab_First_Slot_Desktop_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Component_HorizontalTab_First_Slot_Desktop_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Component_HorizontalTab_First_Slot_Desktop_C_PreConstruct) == 0x000001, "Wrong alignment on UI_Component_HorizontalTab_First_Slot_Desktop_C_PreConstruct");
static_assert(sizeof(UI_Component_HorizontalTab_First_Slot_Desktop_C_PreConstruct) == 0x000001, "Wrong size on UI_Component_HorizontalTab_First_Slot_Desktop_C_PreConstruct");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_Component_HorizontalTab_First_Slot_Desktop.UI_Component_HorizontalTab_First_Slot_Desktop_C.OnSelected
// 0x0001 (0x0001 - 0x0000)
struct UI_Component_HorizontalTab_First_Slot_Desktop_C_OnSelected final
{
public:
	bool                                          bSelected;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Component_HorizontalTab_First_Slot_Desktop_C_OnSelected) == 0x000001, "Wrong alignment on UI_Component_HorizontalTab_First_Slot_Desktop_C_OnSelected");
static_assert(sizeof(UI_Component_HorizontalTab_First_Slot_Desktop_C_OnSelected) == 0x000001, "Wrong size on UI_Component_HorizontalTab_First_Slot_Desktop_C_OnSelected");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_OnSelected, bSelected) == 0x000000, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_OnSelected::bSelected' has a wrong offset!");

// Function UI_Component_HorizontalTab_First_Slot_Desktop.UI_Component_HorizontalTab_First_Slot_Desktop_C.SetStateDesktop
// 0x0170 (0x0170 - 0x0000)
struct UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop final
{
public:
	E_Type_State_Button                           StateDesktop_0;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_Type_State_Button                           Temp_byte_Variable_3;                              // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              Temp_struct_Variable;                              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Temp_struct_Variable_1;                            // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Temp_struct_Variable_2;                            // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_Type_State_Button                           Temp_byte_Variable_4;                              // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_struct_Variable_3;                            // 0x0024(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_4;                            // 0x0034(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_5;                            // 0x0044(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_Type_State_Button                           Temp_byte_Variable_5;                              // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_Type_State_Button                           Temp_byte_Variable_6;                              // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_7;                              // 0x0065(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_8;                              // 0x0066(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_9;                              // 0x0067(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_Type_State_Button                           Temp_byte_Variable_10;                             // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_struct_Variable_6;                            // 0x006C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_7;                            // 0x007C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_8;                            // 0x008C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9D[0x3];                                       // 0x009D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              K2Node_Select_Default_1;                           // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select_Default_2;                           // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo;                   // 0x00B8(0x0068)(HasGetValueTypeHash)
	struct FLinearColor                           K2Node_Select_Default_3;                           // 0x0120(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0130(0x0028)()
	struct FLinearColor                           K2Node_Select_Default_4;                           // 0x0158(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_Type_State_Button                           Temp_byte_Variable_11;                             // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_5;                           // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop) == 0x000008, "Wrong alignment on UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop");
static_assert(sizeof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop) == 0x000170, "Wrong size on UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, StateDesktop_0) == 0x000000, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::StateDesktop_0' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_byte_Variable) == 0x000001, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000002, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_byte_Variable_1) == 0x000003, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_byte_Variable_2) == 0x000004, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_byte_Variable_3) == 0x000005, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_struct_Variable) == 0x000008, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_struct_Variable_1) == 0x000010, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_struct_Variable_2) == 0x000018, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_struct_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_byte_Variable_4) == 0x000020, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_byte_Variable_4' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_struct_Variable_3) == 0x000024, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_struct_Variable_3' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_struct_Variable_4) == 0x000034, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_struct_Variable_4' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_struct_Variable_5) == 0x000044, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_struct_Variable_5' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_byte_Variable_5) == 0x000054, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_byte_Variable_5' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_int_Variable) == 0x000058, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_int_Variable_1) == 0x00005C, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_int_Variable_2) == 0x000060, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_byte_Variable_6) == 0x000064, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_byte_Variable_6' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_byte_Variable_7) == 0x000065, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_byte_Variable_7' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_byte_Variable_8) == 0x000066, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_byte_Variable_8' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_byte_Variable_9) == 0x000067, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_byte_Variable_9' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_byte_Variable_10) == 0x000068, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_byte_Variable_10' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_struct_Variable_6) == 0x00006C, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_struct_Variable_6' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_struct_Variable_7) == 0x00007C, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_struct_Variable_7' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_struct_Variable_8) == 0x00008C, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_struct_Variable_8' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, K2Node_Select_Default) == 0x00009C, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, CallFunc_PlayAnimation_ReturnValue) == 0x0000A0, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, K2Node_Select_Default_1) == 0x0000A8, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, K2Node_Select_Default_2) == 0x0000B0, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, K2Node_MakeStruct_SlateFontInfo) == 0x0000B8, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::K2Node_MakeStruct_SlateFontInfo' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, K2Node_Select_Default_3) == 0x000120, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, K2Node_MakeStruct_SlateColor) == 0x000130, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, K2Node_Select_Default_4) == 0x000158, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, Temp_byte_Variable_11) == 0x000168, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::Temp_byte_Variable_11' has a wrong offset!");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop, K2Node_Select_Default_5) == 0x000169, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_SetStateDesktop::K2Node_Select_Default_5' has a wrong offset!");

// Function UI_Component_HorizontalTab_First_Slot_Desktop.UI_Component_HorizontalTab_First_Slot_Desktop_C.PlayTabSelectedAnim
// 0x0008 (0x0008 - 0x0000)
struct UI_Component_HorizontalTab_First_Slot_Desktop_C_PlayTabSelectedAnim final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Component_HorizontalTab_First_Slot_Desktop_C_PlayTabSelectedAnim) == 0x000008, "Wrong alignment on UI_Component_HorizontalTab_First_Slot_Desktop_C_PlayTabSelectedAnim");
static_assert(sizeof(UI_Component_HorizontalTab_First_Slot_Desktop_C_PlayTabSelectedAnim) == 0x000008, "Wrong size on UI_Component_HorizontalTab_First_Slot_Desktop_C_PlayTabSelectedAnim");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_PlayTabSelectedAnim, CallFunc_PlayAnimation_ReturnValue) == 0x000000, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_PlayTabSelectedAnim::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

// Function UI_Component_HorizontalTab_First_Slot_Desktop.UI_Component_HorizontalTab_First_Slot_Desktop_C.BP_IsNotSelectableOrNavigable
// 0x0001 (0x0001 - 0x0000)
struct UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_IsNotSelectableOrNavigable final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_IsNotSelectableOrNavigable) == 0x000001, "Wrong alignment on UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_IsNotSelectableOrNavigable");
static_assert(sizeof(UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_IsNotSelectableOrNavigable) == 0x000001, "Wrong size on UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_IsNotSelectableOrNavigable");
static_assert(offsetof(UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_IsNotSelectableOrNavigable, ReturnValue) == 0x000000, "Member 'UI_Component_HorizontalTab_First_Slot_Desktop_C_BP_IsNotSelectableOrNavigable::ReturnValue' has a wrong offset!");

}

