#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_HUD_Notice_TeamRebirth

#include "Basic.hpp"

#include "Solarland_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_HUD_Notice_TeamRebirth.UI_HUD_Notice_TeamRebirth_C
// 0x0010 (0x0690 - 0x0680)
class UUI_HUD_Notice_TeamRebirth_C final : public UUINoticeBase
{
public:
	class UWidgetAnimation*                       Anim_Exit;                                         // 0x0680(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anim_Enter;                                        // 0x0688(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_HUD_Notice_TeamRebirth_C">();
	}
	static class UUI_HUD_Notice_TeamRebirth_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_HUD_Notice_TeamRebirth_C>();
	}
};
static_assert(alignof(UUI_HUD_Notice_TeamRebirth_C) == 0x000008, "Wrong alignment on UUI_HUD_Notice_TeamRebirth_C");
static_assert(sizeof(UUI_HUD_Notice_TeamRebirth_C) == 0x000690, "Wrong size on UUI_HUD_Notice_TeamRebirth_C");
static_assert(offsetof(UUI_HUD_Notice_TeamRebirth_C, Anim_Exit) == 0x000680, "Member 'UUI_HUD_Notice_TeamRebirth_C::Anim_Exit' has a wrong offset!");
static_assert(offsetof(UUI_HUD_Notice_TeamRebirth_C, Anim_Enter) == 0x000688, "Member 'UUI_HUD_Notice_TeamRebirth_C::Anim_Enter' has a wrong offset!");

}

