#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_HUD_PickupList_Mark

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Solarland_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_HUD_PickupList_Mark.UI_HUD_PickupList_Mark_C
// 0x0018 (0x0638 - 0x0620)
class UUI_HUD_PickupList_Mark_C final : public UPickupMarkWindowWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0620(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USizeBox*                               SizeBox_Mark;                                      // 0x0628(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          Is_Drag;                                           // 0x0630(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Is_Marked;                                         // 0x0631(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_632[0x2];                                      // 0x0632(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HeightOverride;                                    // 0x0634(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_HUD_PickupList_Mark(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetMarkBg(float InHeightOverride);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_HUD_PickupList_Mark_C">();
	}
	static class UUI_HUD_PickupList_Mark_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_HUD_PickupList_Mark_C>();
	}
};
static_assert(alignof(UUI_HUD_PickupList_Mark_C) == 0x000008, "Wrong alignment on UUI_HUD_PickupList_Mark_C");
static_assert(sizeof(UUI_HUD_PickupList_Mark_C) == 0x000638, "Wrong size on UUI_HUD_PickupList_Mark_C");
static_assert(offsetof(UUI_HUD_PickupList_Mark_C, UberGraphFrame) == 0x000620, "Member 'UUI_HUD_PickupList_Mark_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_HUD_PickupList_Mark_C, SizeBox_Mark) == 0x000628, "Member 'UUI_HUD_PickupList_Mark_C::SizeBox_Mark' has a wrong offset!");
static_assert(offsetof(UUI_HUD_PickupList_Mark_C, Is_Drag) == 0x000630, "Member 'UUI_HUD_PickupList_Mark_C::Is_Drag' has a wrong offset!");
static_assert(offsetof(UUI_HUD_PickupList_Mark_C, Is_Marked) == 0x000631, "Member 'UUI_HUD_PickupList_Mark_C::Is_Marked' has a wrong offset!");
static_assert(offsetof(UUI_HUD_PickupList_Mark_C, HeightOverride) == 0x000634, "Member 'UUI_HUD_PickupList_Mark_C::HeightOverride' has a wrong offset!");

}

