#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_HUD_Video

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Solarland_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_HUD_Video.UI_HUD_Video_C
// 0x0038 (0x0628 - 0x05F0)
class UUI_HUD_Video_C final : public USkydivingVideoWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anim_Exit;                                         // 0x05F8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anim_Enter;                                        // 0x0600(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class USolarTextBlock*                        Txt_City;                                          // 0x0608(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USolarTextBlock*                        Txt_Season;                                        // 0x0610(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USolarTextBlock*                        Txt_Time;                                          // 0x0618(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         WaitTime;                                          // 0x0620(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_HUD_Video(int32 EntryPoint);
	void ShowHUDNotice();
	void OnSolarUIClosed();
	void Construct();
	void OnExitAnimFinish();
	void OnEnterAnimFinish();
	void ShowBattleUIInLua();
	void SetArabic();
	void NotifyHUDVideoEndInLua();
	void NotifyHUDVideoStartInLua();

	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_HUD_Video_C">();
	}
	static class UUI_HUD_Video_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_HUD_Video_C>();
	}
};
static_assert(alignof(UUI_HUD_Video_C) == 0x000008, "Wrong alignment on UUI_HUD_Video_C");
static_assert(sizeof(UUI_HUD_Video_C) == 0x000628, "Wrong size on UUI_HUD_Video_C");
static_assert(offsetof(UUI_HUD_Video_C, UberGraphFrame) == 0x0005F0, "Member 'UUI_HUD_Video_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_HUD_Video_C, Anim_Exit) == 0x0005F8, "Member 'UUI_HUD_Video_C::Anim_Exit' has a wrong offset!");
static_assert(offsetof(UUI_HUD_Video_C, Anim_Enter) == 0x000600, "Member 'UUI_HUD_Video_C::Anim_Enter' has a wrong offset!");
static_assert(offsetof(UUI_HUD_Video_C, Txt_City) == 0x000608, "Member 'UUI_HUD_Video_C::Txt_City' has a wrong offset!");
static_assert(offsetof(UUI_HUD_Video_C, Txt_Season) == 0x000610, "Member 'UUI_HUD_Video_C::Txt_Season' has a wrong offset!");
static_assert(offsetof(UUI_HUD_Video_C, Txt_Time) == 0x000618, "Member 'UUI_HUD_Video_C::Txt_Time' has a wrong offset!");
static_assert(offsetof(UUI_HUD_Video_C, WaitTime) == 0x000620, "Member 'UUI_HUD_Video_C::WaitTime' has a wrong offset!");

}

