#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_OB_Minimap_Btn

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Solarland_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_OB_Minimap_Btn.UI_OB_Minimap_Btn_C
// 0x0028 (0x0618 - 0x05F0)
class UUI_OB_Minimap_Btn_C final : public USolarUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USolarButton*                           Btn_Map_Close;                                     // 0x05F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Map_Close;                                     // 0x0600(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Panel_Map_Close;                                   // 0x0608(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          Off;                                               // 0x0610(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_UI_OB_Minimap_Btn(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetState(bool Off_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_OB_Minimap_Btn_C">();
	}
	static class UUI_OB_Minimap_Btn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_OB_Minimap_Btn_C>();
	}
};
static_assert(alignof(UUI_OB_Minimap_Btn_C) == 0x000008, "Wrong alignment on UUI_OB_Minimap_Btn_C");
static_assert(sizeof(UUI_OB_Minimap_Btn_C) == 0x000618, "Wrong size on UUI_OB_Minimap_Btn_C");
static_assert(offsetof(UUI_OB_Minimap_Btn_C, UberGraphFrame) == 0x0005F0, "Member 'UUI_OB_Minimap_Btn_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_OB_Minimap_Btn_C, Btn_Map_Close) == 0x0005F8, "Member 'UUI_OB_Minimap_Btn_C::Btn_Map_Close' has a wrong offset!");
static_assert(offsetof(UUI_OB_Minimap_Btn_C, Img_Map_Close) == 0x000600, "Member 'UUI_OB_Minimap_Btn_C::Img_Map_Close' has a wrong offset!");
static_assert(offsetof(UUI_OB_Minimap_Btn_C, Panel_Map_Close) == 0x000608, "Member 'UUI_OB_Minimap_Btn_C::Panel_Map_Close' has a wrong offset!");
static_assert(offsetof(UUI_OB_Minimap_Btn_C, Off) == 0x000610, "Member 'UUI_OB_Minimap_Btn_C::Off' has a wrong offset!");

}

