#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Skill_Scan_Common_VX

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Solarland_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Skill_Scan_Common_VX.UI_Skill_Scan_Common_VX_C
// 0x0010 (0x0850 - 0x0840)
class UUI_Skill_Scan_Common_VX_C final : public UWorldMark_ScanActorMark
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0840(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_UI_Skill_Scan_Common_VX(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Skill_Scan_Common_VX_C">();
	}
	static class UUI_Skill_Scan_Common_VX_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Skill_Scan_Common_VX_C>();
	}
};
static_assert(alignof(UUI_Skill_Scan_Common_VX_C) == 0x000010, "Wrong alignment on UUI_Skill_Scan_Common_VX_C");
static_assert(sizeof(UUI_Skill_Scan_Common_VX_C) == 0x000850, "Wrong size on UUI_Skill_Scan_Common_VX_C");
static_assert(offsetof(UUI_Skill_Scan_Common_VX_C, UberGraphFrame) == 0x000840, "Member 'UUI_Skill_Scan_Common_VX_C::UberGraphFrame' has a wrong offset!");

}

