#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Skill_Duration_Super

#include "Basic.hpp"

#include "UI_Skill_Duration_Super_classes.hpp"
#include "UI_Skill_Duration_Super_parameters.hpp"


namespace SDK
{

// Function UI_Skill_Duration_Super.UI_Skill_Duration_Super_C.ExecuteUbergraph_UI_Skill_Duration_Super
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Skill_Duration_Super_C::ExecuteUbergraph_UI_Skill_Duration_Super(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Skill_Duration_Super_C", "ExecuteUbergraph_UI_Skill_Duration_Super");

	Params::UI_Skill_Duration_Super_C_ExecuteUbergraph_UI_Skill_Duration_Super Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Skill_Duration_Super.UI_Skill_Duration_Super_C.WidgetAnimationEvt_Exit_Anim_K2Node_WidgetAnimationEvent_0
// (BlueprintEvent)

void UUI_Skill_Duration_Super_C::WidgetAnimationEvt_Exit_Anim_K2Node_WidgetAnimationEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Skill_Duration_Super_C", "WidgetAnimationEvt_Exit_Anim_K2Node_WidgetAnimationEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}

}

