#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_TabControl_Horizontal_Desktop

#include "Basic.hpp"

#include "UI_TabControl_Horizontal_Desktop_classes.hpp"
#include "UI_TabControl_Horizontal_Desktop_parameters.hpp"


namespace SDK
{

// Function UI_TabControl_Horizontal_Desktop.UI_TabControl_Horizontal_Desktop_C.ExecuteUbergraph_UI_TabControl_Horizontal_Desktop
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TabControl_Horizontal_Desktop_C::ExecuteUbergraph_UI_TabControl_Horizontal_Desktop(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabControl_Horizontal_Desktop_C", "ExecuteUbergraph_UI_TabControl_Horizontal_Desktop");

	Params::UI_TabControl_Horizontal_Desktop_C_ExecuteUbergraph_UI_TabControl_Horizontal_Desktop Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabControl_Horizontal_Desktop.UI_TabControl_Horizontal_Desktop_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_TabControl_Horizontal_Desktop_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabControl_Horizontal_Desktop_C", "PreConstruct");

	Params::UI_TabControl_Horizontal_Desktop_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabControl_Horizontal_Desktop.UI_TabControl_Horizontal_Desktop_C.SetBindWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UListView**                       BindList_0                                             (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TabControl_Horizontal_Desktop_C::SetBindWidget(class UListView** BindList_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabControl_Horizontal_Desktop_C", "SetBindWidget");

	Params::UI_TabControl_Horizontal_Desktop_C_SetBindWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (BindList_0 != nullptr)
		*BindList_0 = Parms.BindList_0;
}


// Function UI_TabControl_Horizontal_Desktop.UI_TabControl_Horizontal_Desktop_C.GetListTap
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USolarListView**                  NewParam                                               (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TabControl_Horizontal_Desktop_C::GetListTap(class USolarListView** NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabControl_Horizontal_Desktop_C", "GetListTap");

	Params::UI_TabControl_Horizontal_Desktop_C_GetListTap Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}

}

