#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Weapon_Part_HUDWeapon_Desktop

#include "Basic.hpp"

#include "Solarland_structs.hpp"
#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function UI_Weapon_Part_HUDWeapon_Desktop.UI_Weapon_Part_HUDWeapon_Desktop_C.Set Full Weapon Parts
// 0x000C (0x000C - 0x0000)
struct UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts final
{
public:
	bool                                          IsFullEquipedParts_0;                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	EWeaponPartSlotMode                           EWeaponPartsMode_0;                                // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EWeaponPartSlotMode                           Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EWeaponPartSlotMode                           Temp_byte_Variable_4;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_5;                              // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_6;                              // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_7;                              // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts) == 0x000001, "Wrong alignment on UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts");
static_assert(sizeof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts) == 0x00000C, "Wrong size on UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts, IsFullEquipedParts_0) == 0x000000, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts::IsFullEquipedParts_0' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts, EWeaponPartsMode_0) == 0x000001, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts::EWeaponPartsMode_0' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts, Temp_byte_Variable) == 0x000002, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts, Temp_byte_Variable_1) == 0x000003, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts, Temp_byte_Variable_2) == 0x000004, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts, Temp_byte_Variable_3) == 0x000005, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts, Temp_byte_Variable_4) == 0x000006, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts::Temp_byte_Variable_4' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts, K2Node_Select_Default) == 0x000007, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts, Temp_byte_Variable_5) == 0x000008, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts::Temp_byte_Variable_5' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts, Temp_byte_Variable_6) == 0x000009, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts::Temp_byte_Variable_6' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts, Temp_byte_Variable_7) == 0x00000A, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts::Temp_byte_Variable_7' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts, K2Node_Select_Default_1) == 0x00000B, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_Set_Full_Weapon_Parts::K2Node_Select_Default_1' has a wrong offset!");

// Function UI_Weapon_Part_HUDWeapon_Desktop.UI_Weapon_Part_HUDWeapon_Desktop_C.SetArrow
// 0x0005 (0x0005 - 0x0000)
struct UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow final
{
public:
	bool                                          bInShow;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow) == 0x000001, "Wrong alignment on UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow");
static_assert(sizeof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow) == 0x000005, "Wrong size on UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow, bInShow) == 0x000000, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow::bInShow' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow, Temp_bool_Variable) == 0x000001, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow, Temp_byte_Variable) == 0x000002, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow, Temp_byte_Variable_1) == 0x000003, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow, K2Node_Select_Default) == 0x000004, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_SetArrow::K2Node_Select_Default' has a wrong offset!");

// Function UI_Weapon_Part_HUDWeapon_Desktop.UI_Weapon_Part_HUDWeapon_Desktop_C.SetSize
// 0x0008 (0x0008 - 0x0000)
struct UI_Weapon_Part_HUDWeapon_Desktop_C_SetSize final
{
public:
	int32                                         inInt;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetSize) == 0x000004, "Wrong alignment on UI_Weapon_Part_HUDWeapon_Desktop_C_SetSize");
static_assert(sizeof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetSize) == 0x000008, "Wrong size on UI_Weapon_Part_HUDWeapon_Desktop_C_SetSize");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetSize, inInt) == 0x000000, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_SetSize::inInt' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetSize, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000004, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_SetSize::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");

// Function UI_Weapon_Part_HUDWeapon_Desktop.UI_Weapon_Part_HUDWeapon_Desktop_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Weapon_Part_HUDWeapon_Desktop_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Weapon_Part_HUDWeapon_Desktop_C_PreConstruct) == 0x000001, "Wrong alignment on UI_Weapon_Part_HUDWeapon_Desktop_C_PreConstruct");
static_assert(sizeof(UI_Weapon_Part_HUDWeapon_Desktop_C_PreConstruct) == 0x000001, "Wrong size on UI_Weapon_Part_HUDWeapon_Desktop_C_PreConstruct");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_Weapon_Part_HUDWeapon_Desktop.UI_Weapon_Part_HUDWeapon_Desktop_C.BP_SetShowArrow
// 0x0001 (0x0001 - 0x0000)
struct UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetShowArrow final
{
public:
	bool                                          bIsShow;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetShowArrow) == 0x000001, "Wrong alignment on UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetShowArrow");
static_assert(sizeof(UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetShowArrow) == 0x000001, "Wrong size on UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetShowArrow");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetShowArrow, bIsShow) == 0x000000, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetShowArrow::bIsShow' has a wrong offset!");

// Function UI_Weapon_Part_HUDWeapon_Desktop.UI_Weapon_Part_HUDWeapon_Desktop_C.BP_SetStyle
// 0x0002 (0x0002 - 0x0000)
struct UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetStyle final
{
public:
	bool                                          bIsFullyPart;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	EWeaponPartSlotMode                           InSlotMode;                                        // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetStyle) == 0x000001, "Wrong alignment on UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetStyle");
static_assert(sizeof(UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetStyle) == 0x000002, "Wrong size on UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetStyle");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetStyle, bIsFullyPart) == 0x000000, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetStyle::bIsFullyPart' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetStyle, InSlotMode) == 0x000001, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_BP_SetStyle::InSlotMode' has a wrong offset!");

// Function UI_Weapon_Part_HUDWeapon_Desktop.UI_Weapon_Part_HUDWeapon_Desktop_C.SetPickupAnimByQualityBP
// 0x0004 (0x0004 - 0x0000)
struct UI_Weapon_Part_HUDWeapon_Desktop_C_SetPickupAnimByQualityBP final
{
public:
	int32                                         InQuality;                                         // 0x0000(0x0004)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetPickupAnimByQualityBP) == 0x000004, "Wrong alignment on UI_Weapon_Part_HUDWeapon_Desktop_C_SetPickupAnimByQualityBP");
static_assert(sizeof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetPickupAnimByQualityBP) == 0x000004, "Wrong size on UI_Weapon_Part_HUDWeapon_Desktop_C_SetPickupAnimByQualityBP");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_SetPickupAnimByQualityBP, InQuality) == 0x000000, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_SetPickupAnimByQualityBP::InQuality' has a wrong offset!");

// Function UI_Weapon_Part_HUDWeapon_Desktop.UI_Weapon_Part_HUDWeapon_Desktop_C.ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop
// 0x02C0 (0x02C0 - 0x0000)
struct UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_1;                            // 0x0014(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_2;                            // 0x0024(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EWeaponPartSlotMode                           Temp_byte_Variable;                                // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable;                               // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_1;                             // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_2;                             // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_3;                             // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_4;                             // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_5;                             // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_6;                             // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_7;                             // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_8;                             // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_9;                             // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_10;                            // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_11;                            // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_12;                            // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_13;                            // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_14;                            // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_15;                            // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_16;                            // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_17;                            // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_18;                            // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_19;                            // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_20;                            // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_21;                            // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_22;                            // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_23;                            // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_24;                            // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_25;                            // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_26;                            // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_27;                            // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_28;                            // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_29;                            // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_30;                            // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x00C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bIsShow;                              // 0x00C5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bIsFullyPart;                         // 0x00C6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EWeaponPartSlotMode                           K2Node_Event_InSlotMode;                           // 0x00C7(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default;                             // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EWeaponPartSlotMode                           Temp_byte_Variable_1;                              // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CD[0x3];                                       // 0x00CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Event_InQuality;                            // 0x00D0(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_Select_Default_1;                           // 0x00D4(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_2;                           // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x00E8(0x0028)()
	struct FSlateBrushOutlineSettings             K2Node_MakeStruct_SlateBrushOutlineSettings;       // 0x0110(0x0040)()
	float                                         K2Node_Select_Default_3;                           // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_154[0xC];                                      // 0x0154(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush;                      // 0x0160(0x0110)()
	float                                         K2Node_Select_Default_4;                           // 0x0270(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_5;                           // 0x0274(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USolarGameInstanceBase*                 CallFunc_GetSolarGameInstanceBase_ReturnValue;     // 0x0278(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x0280(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0290(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_291[0x7];                                      // 0x0291(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USolarGameConfigManager*                CallFunc_GetGameConfigManager_ReturnValue;         // 0x0298(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x02A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A1[0x3];                                      // 0x02A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_GetHUDColorByQuality_ReturnValue;         // 0x02A4(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B4[0x4];                                      // 0x02B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCanvasPanelSlot*                       CallFunc_SlotAsCanvasSlot_ReturnValue;             // 0x02B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop) == 0x000010, "Wrong alignment on UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop");
static_assert(sizeof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop) == 0x0002C0, "Wrong size on UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, EntryPoint) == 0x000000, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_struct_Variable) == 0x000004, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_struct_Variable_1) == 0x000014, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_struct_Variable_2) == 0x000024, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_struct_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_byte_Variable) == 0x000034, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable) == 0x000038, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_1) == 0x00003C, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_2) == 0x000040, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_int_Variable) == 0x000044, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_3) == 0x000048, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_3' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_4) == 0x00004C, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_4' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_5) == 0x000050, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_5' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_6) == 0x000054, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_6' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_7) == 0x000058, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_7' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_8) == 0x00005C, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_8' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_9) == 0x000060, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_9' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_int_Variable_1) == 0x000064, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_10) == 0x000068, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_10' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_11) == 0x00006C, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_11' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_12) == 0x000070, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_12' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_13) == 0x000074, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_13' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_14) == 0x000078, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_14' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_15) == 0x00007C, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_15' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_16) == 0x000080, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_16' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_int_Variable_2) == 0x000084, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_17) == 0x000088, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_17' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_18) == 0x00008C, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_18' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_19) == 0x000090, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_19' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_20) == 0x000094, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_20' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_21) == 0x000098, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_21' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_22) == 0x00009C, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_22' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_23) == 0x0000A0, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_23' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_int_Variable_3) == 0x0000A4, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_int_Variable_3' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_24) == 0x0000A8, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_24' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_25) == 0x0000AC, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_25' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_26) == 0x0000B0, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_26' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_27) == 0x0000B4, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_27' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_28) == 0x0000B8, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_28' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_29) == 0x0000BC, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_29' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_float_Variable_30) == 0x0000C0, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_float_Variable_30' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_Event_IsDesignTime) == 0x0000C4, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_Event_bIsShow) == 0x0000C5, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_Event_bIsShow' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_Event_bIsFullyPart) == 0x0000C6, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_Event_bIsFullyPart' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_Event_InSlotMode) == 0x0000C7, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_Event_InSlotMode' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_Select_Default) == 0x0000C8, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, Temp_byte_Variable_1) == 0x0000CC, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_Event_InQuality) == 0x0000D0, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_Event_InQuality' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_Select_Default_1) == 0x0000D4, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_Select_Default_2) == 0x0000E4, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_MakeStruct_SlateColor) == 0x0000E8, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_MakeStruct_SlateBrushOutlineSettings) == 0x000110, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_MakeStruct_SlateBrushOutlineSettings' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_Select_Default_3) == 0x000150, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_MakeStruct_SlateBrush) == 0x000160, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_MakeStruct_SlateBrush' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_Select_Default_4) == 0x000270, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_Select_Default_5) == 0x000274, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_Select_Default_5' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, CallFunc_GetSolarGameInstanceBase_ReturnValue) == 0x000278, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::CallFunc_GetSolarGameInstanceBase_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, K2Node_MakeStruct_Margin) == 0x000280, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::K2Node_MakeStruct_Margin' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, CallFunc_IsValid_ReturnValue) == 0x000290, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, CallFunc_GetGameConfigManager_ReturnValue) == 0x000298, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::CallFunc_GetGameConfigManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, CallFunc_IsValid_ReturnValue_1) == 0x0002A0, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, CallFunc_GetHUDColorByQuality_ReturnValue) == 0x0002A4, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::CallFunc_GetHUDColorByQuality_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop, CallFunc_SlotAsCanvasSlot_ReturnValue) == 0x0002B8, "Member 'UI_Weapon_Part_HUDWeapon_Desktop_C_ExecuteUbergraph_UI_Weapon_Part_HUDWeapon_Desktop::CallFunc_SlotAsCanvasSlot_ReturnValue' has a wrong offset!");

}

