#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VehicleAnimLayerInterface

#include "Basic.hpp"

#include "VehicleAnimLayerInterface_classes.hpp"
#include "VehicleAnimLayerInterface_parameters.hpp"


namespace SDK
{

// Function VehicleAnimLayerInterface.VehicleAnimLayerInterface_C.VehicleLocamotion
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       bpp__VehicleLocamotion__pf                             (Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)

void IVehicleAnimLayerInterface_C::VehicleLocamotion(struct FPoseLink* bpp__VehicleLocamotion__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("VehicleAnimLayerInterface_C", "VehicleLocamotion");

	Params::VehicleAnimLayerInterface_C_VehicleLocamotion Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (bpp__VehicleLocamotion__pf != nullptr)
		*bpp__VehicleLocamotion__pf = std::move(Parms.bpp__VehicleLocamotion__pf);
}

}

