#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SolarMovablePad

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Solarland_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SolarMovablePad.WBP_SolarMovablePad_C
// 0x0020 (0x09C0 - 0x09A0)
class UWBP_SolarMovablePad_C final : public USolarMovablePad
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x09A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FLinearColor                           BgColor;                                           // 0x09A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsUseCustomBgColor;                               // 0x09B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_WBP_SolarMovablePad(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void Set_Bg_Color(const struct FLinearColor& BgColor_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_SolarMovablePad_C">();
	}
	static class UWBP_SolarMovablePad_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SolarMovablePad_C>();
	}
};
static_assert(alignof(UWBP_SolarMovablePad_C) == 0x000010, "Wrong alignment on UWBP_SolarMovablePad_C");
static_assert(sizeof(UWBP_SolarMovablePad_C) == 0x0009C0, "Wrong size on UWBP_SolarMovablePad_C");
static_assert(offsetof(UWBP_SolarMovablePad_C, UberGraphFrame) == 0x0009A0, "Member 'UWBP_SolarMovablePad_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_SolarMovablePad_C, BgColor) == 0x0009A8, "Member 'UWBP_SolarMovablePad_C::BgColor' has a wrong offset!");
static_assert(offsetof(UWBP_SolarMovablePad_C, bIsUseCustomBgColor) == 0x0009B8, "Member 'UWBP_SolarMovablePad_C::bIsUseCustomBgColor' has a wrong offset!");

}

