#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WorldMark_FrameType

#include "Basic.hpp"

#include "WorldMark_FrameType_classes.hpp"
#include "WorldMark_FrameType_parameters.hpp"


namespace SDK
{

// Function WorldMark_FrameType.WorldMark_FrameType_C.ExecuteUbergraph_WorldMark_FrameType
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWorldMark_FrameType_C::ExecuteUbergraph_WorldMark_FrameType(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WorldMark_FrameType_C", "ExecuteUbergraph_WorldMark_FrameType");

	Params::WorldMark_FrameType_C_ExecuteUbergraph_WorldMark_FrameType Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WorldMark_FrameType.WorldMark_FrameType_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWorldMark_FrameType_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WorldMark_FrameType_C", "PreConstruct");

	Params::WorldMark_FrameType_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WorldMark_FrameType.WorldMark_FrameType_C.SetFrameByWorldMarkData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FWorldMarkData&            WorldMarkData                                          (BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)

void UWorldMark_FrameType_C::SetFrameByWorldMarkData(const struct FWorldMarkData& WorldMarkData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WorldMark_FrameType_C", "SetFrameByWorldMarkData");

	Params::WorldMark_FrameType_C_SetFrameByWorldMarkData Parms{};

	Parms.WorldMarkData = std::move(WorldMarkData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WorldMark_FrameType.WorldMark_FrameType_C.SetFrameType
// (Public, BlueprintCallable, BlueprintEvent)

void UWorldMark_FrameType_C::SetFrameType()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WorldMark_FrameType_C", "SetFrameType");

	UObject::ProcessEvent(Func, nullptr);
}

}

